;;;; inspect/chaos-test.lisp — the node scenarios under an adversarial relay:
;;;; asynchronous delivery, delays, reordering, duplicates.

(in-package #:cl-deposits.test)

(defvar *chaos-seed* (let ((s (uiop:getenv "CHAOS_SEED"))) (if s (parse-integer s) (random 100000 (make-random-state t)))))
(format t "      chaos seed ~a~%" *chaos-seed*)
(defvar *height* 1000)

(defun settled (bus) (or (bus:bus-settle bus) (progn (format t "      (bus did not settle)~%") nil)))

(with-gate ("chaos: quorum formation, deposits, a transfer, and a dispute under an adversarial relay")
  (let* ((bus (bus:make-chaos-bus :seed *chaos-seed* :max-delay 0.03 :window 4 :dup-rate 0.15))
         (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:chaos" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m))))
    (check "settles after genesis" (settled bus))
    (dolist (m (list b c d)) (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (check "settles after membership" (settled bus))
    (check-equal "three staged despite duplicates and reordering" (length (lg:ledger-next-quorum-members (nd:record-ledger la))) 3)
    (check "each member joined exactly once (duplicate consent requests ignored)"
           (every (lambda (m) (= 1 (length (lg:ledger-joined-quorums (nd:record-ledger (nd:own-ledger m)))))) (list b c d)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "c4a05")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (check "settles after QuorumBegin" (settled bus))
    (check "replicas converge to A's tip" (every (lambda (m) (equalp (lg:ledger-chain-tip (nd:record-ledger (nd:find-record m id))) (lg:ledger-chain-tip (nd:record-ledger la)))) (list b c d)))
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (d1 (nd:wallet-open-deposit w1 id)) (d2 (nd:wallet-open-deposit w2 id)))
      (nd:credit-onchain a la d1 100000 :txid (u:sha256 (hx "c0")))
      ;; a burst: several operations in flight at once
      (multiple-value-bind (tid pre)
          (handler-case (nd:wallet-transfer w1 id d1 d2 40000 :height *height*)
            (error (e) (format t "      transfer failed: ~a~%      a: ~{~a~^ | ~}~%      b: ~{~a~^ | ~}~%      c: ~{~a~^ | ~}~%      d: ~{~a~^ | ~}~%" e
                               (reverse (nd:node-log a)) (reverse (nd:node-log b)) (reverse (nd:node-log c)) (reverse (nd:node-log d)))
              (error e)))
        (handler-case (nd:wallet-complete-transfer w1 id tid pre)
          (error (e) (format t "      complete failed: ~a~%      b: ~{~a~^ | ~}~%      c: ~{~a~^ | ~}~%      d: ~{~a~^ | ~}~%" e
                             (reverse (nd:node-log b)) (reverse (nd:node-log c)) (reverse (nd:node-log d)))
            (error e))))
      (nd:credit-onchain a la d2 1000 :txid (u:sha256 (hx "c1")))
      (check "settles after the burst" (settled bus))
      (check-equal "balances" (list (nd:wallet-balance w1 id d1) (nd:wallet-balance w2 id d2)) '(60000 41000))
      (check "replicas at A's tip after the burst"
             (every (lambda (m) (equalp (lg:ledger-chain-tip (nd:record-ledger (nd:find-record m id))) (lg:ledger-chain-tip (nd:record-ledger la)))) (list b c d)))
      (check "no replica applied an update twice (history length = seq + 1)"
             (every (lambda (m) (let ((r (nd:find-record m id))) (= (length (nd:record-history r)) (1+ (lg:ledger-sequence (nd:record-ledger r)))))) (list b c d)))
      ;; Dispute under chaos: equivocation detected, forks, arming, confiscation, claim.
      (nd:equivocate a la)
      (check "settles after the equivocation" (settled bus))
      (check "every member forked" (every (lambda (m) (nd:find-fork m id (nd:node-pubkey m))) (list b c d)))
      (check "every member sees three forks" (every (lambda (m) (= 3 (length (nd:forks-of m id)))) (list b c d)))
      (dolist (m (list b c d)) (nd:arm-dispute m (nd:find-fork m id (nd:node-pubkey m))))
      (check "settles after arming" (settled bus))
      (check "everyone sees three armers" (every (lambda (m) (= 3 (length (nd:armers-of m id)))) (list b c d)))
      (multiple-value-bind (ctx lottery) (handler-case (nd:confiscate b id)
                                         (error (e) (format t "      confiscate failed: ~a~%" e) (dolist (m (list b c d)) (format t "      ~a log: ~{~a~^ | ~}~%" (subseq (nd:node-pubkey-hex m) 0 4) (reverse (nd:node-log m)))) (error e)))
        (declare (ignore lottery))
        (check "confiscation assembled under chaos" (and ctx t))
        (check "settles after confiscation" (settled bus))
        (dolist (m (list b c d)) (nd:publish-reveal m id))
        (check "settles after reveals" (settled bus))
        (check "all reveals collected everywhere" (every (lambda (m) (= 3 (length (nd:reveals-of m id)))) (list b c d)))
        (let ((outcomes (mapcar (lambda (m) (first (multiple-value-list (nd:claim-or-yield m id)))) (list b c d))))
          (check "settles after claims" (settled bus))
          (check-equal "exactly one winner" (count :won outcomes) 1))))
    (format t "      logs: ~{~a~^ | ~}~%" (subseq (reverse (append (nd:node-log a) (nd:node-log b))) 0 (min 6 (length (append (nd:node-log a) (nd:node-log b))))))))

(with-gate ("chaos: couriers under an adversarial relay")
  (let* ((bus (bus:make-chaos-bus :seed (1+ *chaos-seed*) :max-delay 0.02 :window 3 :dup-rate 0.1))
         (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf)) (e (nd:make-node :priv 99999999999999999999 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf)) (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf)) (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (kn (nd:make-node :priv 77777777777777777777 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:ca" :reserves 15600000 :collateral 23400000)) (le (nd:open-ledger e :reserves-id "genesis:ce" :reserves 15600000 :collateral 23400000))
         (ida (nd:record-id-hex la)) (ide (nd:record-id-hex le)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m))))
    (settled bus)
    (dolist (opnode (list a e))
      (let ((rec (if (eq opnode a) la le)))
        (dolist (m (list b c d)) (nd:add-member opnode rec (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
        (nd:begin-quorum opnode rec :funding-txid (u:sha256 (u:cat (hx "c4a0") (nd:node-pubkey opnode))) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)))
    (check "settles after two quorums" (settled bus))
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (kwa (nd:make-wallet :priv 77777777777777777777 :bus bus)) (kwe (nd:make-wallet :priv 77777777777777777777 :bus bus))
           (d1 (nd:wallet-open-deposit w1 ida)) (d2 (nd:wallet-open-deposit w2 ide)) (ka (nd:wallet-open-deposit kwa ida)) (ke (nd:wallet-open-deposit kwe ide))
           (k (cr:make-courier kn)))
      (nd:credit-onchain a la d1 500000 :txid (u:sha256 (hx "c2"))) (nd:credit-onchain e le ke 800000 :txid (u:sha256 (hx "c3")))
      (settled bus)
      (cr:courier-serve k ida ka kwa) (cr:courier-serve k ide ke kwe)
      (multiple-value-bind (leg1 preimage forward)
          (handler-case (cr:wallet-route w1 (nd:node-pubkey-hex kn) ida ide d1 d2 100000 :height *height*)
            (error (er) (format t "      route failed: ~a~%      a: ~{~a~^ | ~}~%      b: ~{~a~^ | ~}~%      c: ~{~a~^ | ~}~%      d: ~{~a~^ | ~}~%      k: ~{~a~^ | ~}~%" er
                                (reverse (nd:node-log a)) (reverse (nd:node-log b)) (reverse (nd:node-log c)) (reverse (nd:node-log d)) (reverse (nd:node-log kn)))
              (error er)))
        (declare (ignore leg1))
        (check "settles after leg 1" (settled bus))
        (let ((leg2 (nd:wallet-pending-lock kn ide (u:sha256 preimage) d2)))
          (check "courier locked leg 2 despite delays and duplicates" (and leg2 t))
          (when leg2
            (nd:wallet-complete-transfer w2 ide (getf leg2 :transfer-id) preimage)
            (check "settles after completion" (settled bus))
            (check-equal "receiver got the forward amount" (nd:wallet-balance w2 ide d2) forward)
            (check-equal "courier collected leg 1 exactly once" (nd:wallet-balance kwa ida ka) 100000)))))))

(report)
