;;;; inspect/lottery-test.lisp — the custody lottery, spent under cl-consensus.

(in-package #:cl-deposits.test)

(defun lot-keys (n) (loop for i from 1 to n collect (+ 424242424242 (* i 1000000007))))
(defun xonly-of (priv) (up:x-only (up:compressed-pubkey priv)))

(defun random-preimage (&optional (range lot:+contribution-range+))
  (let ((len (+ 17 (random range))))
    (let ((p (make-array len :element-type '(unsigned-byte 8)))) (dotimes (i len p) (setf (aref p i) (random 256))))))

(with-gate ("lottery: winner rule and preimage derivation")
  (check-equal "sum of contributions mod n" (lot:calculate-winner (list (make-array 18) (make-array 19) (make-array 17))) (mod (+ 2 3 1) 3))
  (check-signals "short preimage rejected" error (lot:calculate-winner (list (make-array 16) (make-array 17))))
  (check-signals "a 77-byte preimage is rejected" error (lot:calculate-winner (list (make-array 77) (make-array 17))))
  (check-equal "a 76-byte preimage contributes 60" (lot:calculate-winner (list (make-array 76) (make-array 17))) (mod 61 2))
  (check-equal "subset winner indexes the full order" (lot:subset-winner '(1 3 4) (list (make-array 17) (make-array 17) (make-array 17))) 1)
  (let ((p (lot:derive-preimage (u:sha256 (hx "01")))))
    (check "derived preimage length in 17..76" (<= 17 (length p) 76))
    (check-bytes "derivation is deterministic" (lot:derive-preimage (u:sha256 (hx "01"))) p))
  (check-equal "lengths spread over all 60"
               (length (remove-duplicates (loop for i below 2000 collect (length (lot:derive-preimage (u:sha256 (u:int->be i 4)))))))
               60)
  (check-equal "subsets of 3: by size, then lexicographic" (lot::subset-indices 3) '((0 1) (0 2) (1 2) (0) (1) (2)))
  (check-equal "126 proper subsets of 7" (length (lot::subset-indices 7)) 126)
  (check-equal "tree shape: 6 leaves -> depths 3 3 3 3 2 2" (lot::leaf-depths 6) '(3 3 3 3 2 2))
  (check-equal "tree shape: 8 leaves all depth 3" (lot::leaf-depths 8) '(3 3 3 3 3 3 3 3))
  (check-equal "tree shape: 5 leaves -> 3 3 2 2 2" (lot::leaf-depths 5) '(3 3 2 2 2)))

(defun spend-lottery (l amount witness-fn &key (sequence #xfffffffd) (dest-xonly (xonly-of 7)))
  "Build a claim of the lottery output paying DEST, attach WITNESS-FN's stack, verify."
  (let* ((prevouts (vector (cons amount (lot:lottery-spk l))))
         (tx (rot:build-spend :prev-txid (u:sha256 (hx "1077")) :prev-vout 0 :reserves-amount amount
                              :destination-spk (lot:key-path-spk dest-xonly) :fee-rate 1))
         (tx (btx:parse-tx (cl-consensus.wire:make-reader
                            (btx:serialize-tx (btx:make-tx :version 2 :locktime 0 :segwit-p t
                                                           :inputs (list (btx:make-txin :prev-hash (u:sha256 (hx "1077")) :prev-index 0 :script (u:octets) :sequence sequence))
                                                           :outputs (btx:tx-outputs tx) :witnesses (list nil))))))
         (stack (funcall witness-fn tx prevouts))
         (signed (btx:parse-tx (cl-consensus.wire:make-reader
                                (btx:serialize-tx (btx:make-tx :version 2 :locktime 0 :segwit-p t :inputs (btx:tx-inputs tx)
                                                               :outputs (btx:tx-outputs tx) :witnesses (list stack)))))))
    (rot:verify-spend signed 0 prevouts)))

(defun sig-for (l tx prevouts leaf priv)
  (declare (ignore l))
  (secp256k1-fast.schnorr:schnorr-sign priv (rot:tier-sighash tx 0 prevouts leaf)))

(dolist (n '(2 3 5 7))
  (with-gate ((format nil "lottery: k=~a, every revealer subset, spent under consensus" n))
    (let* ((privs (lot-keys n))
           (preimages (loop repeat n collect (random-preimage)))
           (participants (loop for priv in privs for p in preimages
                               collect (lot:make-participant :pubkey (xonly-of priv) :commitment (lot:commitment-of p) :target "tb1p")))
           (vprivs (lot-keys 3))
           (voters (mapcar #'xonly-of vprivs))
           (l (lot:build-lottery participants voters 2))
           ;; canonical order is by pubkey: realign preimages/privs to it
           (order (mapcar (lambda (p) (position (lot:participant-pubkey p) participants :key #'lot:participant-pubkey :test #'equalp)) (lot:lottery-participants l)))
           (ordered-pre (mapcar (lambda (i) (nth i preimages)) order))
           (ordered-priv (mapcar (lambda (i) (nth i privs)) order))
           (winner (lot:calculate-winner ordered-pre))
           (amount 1000000))
      (labels ((voter-sigs (tx pv leaf signers)
                 (mapcar (lambda (k) (let ((p (find k vprivs :key #'xonly-of :test #'equalp)))
                                       (and (member p signers) (sig-for l tx pv leaf p))))
                         (lot::sorted-keys voters)))
               (subset-claim (idx claimant-pos &key (signers (list (first vprivs) (third vprivs))) (sequence 72) (pre ordered-pre))
                 (let ((leaf (nth (lot:subset-leaf-index l idx) (lot:lottery-leaves l))))
                   (spend-lottery l amount (lambda (tx pv) (lot:subset-witness l idx (sig-for l tx pv leaf (nth claimant-pos ordered-priv))
                                                                               (mapcar (lambda (i) (nth i pre)) idx)
                                                                               (voter-sigs tx pv leaf signers)))
                                  :sequence sequence))))
        (check "address is p2tr" (string= "tb1p" (subseq (lot:lottery-address l) 0 4)))
        (check-equal "leaf count = full set + 2^k-2 subsets + 4 recovery" (length (lot:lottery-leaves l)) (+ 1 (- (expt 2 n) 2) 4))
        (check (format nil "full set: winner ~a's claim verifies" winner)
               (spend-lottery l amount (lambda (tx pv) (lot:claim-witness l (sig-for l tx pv (first (lot:lottery-leaves l)) (nth winner ordered-priv)) ordered-pre))))
        (check "full set: every loser's claim fails"
               (loop for i below n
                     always (or (= i winner)
                                (not (spend-lottery l amount (lambda (tx pv) (lot:claim-witness l (sig-for l tx pv (first (lot:lottery-leaves l)) (nth i ordered-priv)) ordered-pre)))))))
        (check "full set: a wrong preimage fails"
               (not (spend-lottery l amount (lambda (tx pv) (let ((bad (copy-list ordered-pre))) (setf (first bad) (random-preimage))
                                                               (lot:claim-witness l (sig-for l tx pv (first (lot:lottery-leaves l)) (nth winner ordered-priv)) bad))))))
        ;; Each single withholder: the other k-1 draw among themselves after CSV 72, attested 2 of 3.
        (dotimes (missing n)
          (let* ((idx (loop for i below n unless (= i missing) collect i))
                 (w (lot:subset-winner idx (mapcar (lambda (i) (nth i ordered-pre)) idx))))
            (check (format nil "withholder ~a: R's winner ~a claims after CSV 72 with 2 attestations" missing w) (subset-claim idx w))
            (when (= missing 0)
              (check "the subset claim before CSV 72 fails" (not (subset-claim idx w :sequence 71)))
              (check "one attestation is not enough" (not (subset-claim idx w :signers (list (first vprivs)))))
              (check "the withholder cannot claim R's leaf" (not (subset-claim idx missing)))
              (when (> (length idx) 1)
                (check "another revealer cannot claim R's leaf" (not (subset-claim idx (find-if (lambda (i) (/= i w)) idx)))))
              (check "the withheld preimage cannot be swapped in"
                     (not (subset-claim idx w :pre (let ((b (copy-list ordered-pre))) (setf (nth (first idx) b) (random-preimage)) b)))))))
        (when (>= n 3)
          (let* ((idx (loop for i from 2 below n collect i))
                 (w (lot:subset-winner idx (mapcar (lambda (i) (nth i ordered-pre)) idx))))
            (check (format nil "two withholders: the remaining ~a draw, winner ~a" (length idx) w) (subset-claim idx w))))
        (check "a sole revealer takes it after CSV 72 with attestation" (subset-claim (list (1- n)) (1- n)))
        ;; Nobody revealed: recovery cascade (2-of-3 after 144; T-1=1 after 1008; escape hatch after 8064).
        (let* ((lowest (find (first (lot::sorted-keys voters)) vprivs :key #'xonly-of :test #'equalp))
               (other (find-if (lambda (p) (not (eql p lowest))) vprivs)))
          (flet ((rec (tier csv signers)
                   (spend-lottery l amount
                                  (lambda (tx pv)
                                    (let* ((idx (lot::recovery-leaf-index l tier)) (leaf (nth idx (lot:lottery-leaves l))))
                                      (lot:recovery-witness l tier (voter-sigs tx pv leaf signers))))
                                  :sequence csv)))
            (check "recovery tier 0: 2 of 3 voters after 144 blocks" (rec 0 144 (list (first vprivs) (third vprivs))))
            (check "recovery tier 0: 1 voter is not enough" (not (rec 0 144 (list (first vprivs)))))
            (check "recovery tier 0: too early fails" (not (rec 0 100 (list (first vprivs) (third vprivs)))))
            (check "recovery tier 1 (T-1=1): the lowest sorted voter after 1008" (rec 1 1008 (list lowest)))
            (check "recovery tier 1: another voter cannot use the single-key leaf" (not (rec 1 1008 (list other))))
            (check "escape hatch: the lowest sorted voter after 8064" (rec 3 8064 (list lowest)))
            (check "escape hatch: too early fails" (not (rec 3 8000 (list lowest))))))))))

(with-gate ("lottery: maximum contributions reduce correctly (k=7, all 76 bytes)")
  (let* ((n 7) (privs (lot-keys n))
         (pre (loop for i below n collect (let ((p (make-array 76 :element-type '(unsigned-byte 8)))) (dotimes (j 76 p) (setf (aref p j) (random 256))))))
         (parts (loop for priv in privs for p in pre collect (lot:make-participant :pubkey (xonly-of priv) :commitment (lot:commitment-of p) :target "tb1p")))
         (l (lot:build-lottery parts (mapcar #'xonly-of (lot-keys 3)) 2))
         (order (mapcar (lambda (p) (position (lot:participant-pubkey p) parts :key #'lot:participant-pubkey :test #'equalp)) (lot:lottery-participants l)))
         (opre (mapcar (lambda (i) (nth i pre)) order)) (opriv (mapcar (lambda (i) (nth i privs)) order))
         (w (lot:calculate-winner opre)))
    (check-equal "sum 420 mod 7 = 0" w 0)
    (check "the winner of an all-maximum draw claims" (spend-lottery l 500000 (lambda (tx pv) (lot:claim-witness l (sig-for l tx pv (first (lot:lottery-leaves l)) (nth w opriv)) opre))))))

(with-gate ("lottery: armer shares and forfeit sweep")
  (let* ((armer 55555) (pre (random-preimage)) (voters (mapcar #'xonly-of (lot-keys 3))) (vprivs (lot-keys 3))
         (a (lot:build-armer-share (xonly-of armer) (lot:commitment-of pre) voters 2))
         (amount 50000)
         (prevouts (vector (cons amount (lot:armer-share-spk a)))))
    (flet ((spend (witness-fn sequence)
             (let* ((tx (btx:parse-tx (cl-consensus.wire:make-reader
                                       (btx:serialize-tx (btx:make-tx :version 2 :locktime 0 :segwit-p t
                                                                      :inputs (list (btx:make-txin :prev-hash (u:sha256 (hx "a5")) :prev-index 0 :script (u:octets) :sequence sequence))
                                                                      :outputs (list (btx:make-txout :value (- amount 500) :script (lot:key-path-spk (xonly-of armer)))) :witnesses (list nil))))))
                    (stack (funcall witness-fn tx))
                    (signed (btx:parse-tx (cl-consensus.wire:make-reader (btx:serialize-tx (btx:make-tx :version 2 :locktime 0 :segwit-p t :inputs (btx:tx-inputs tx) :outputs (btx:tx-outputs tx) :witnesses (list stack)))))))
               (rot:verify-spend signed 0 prevouts))))
      (check "armer reveals and claims their share"
             (spend (lambda (tx) (list (sig-for nil tx prevouts (first (lot:armer-share-leaves a)) armer) pre (first (lot:armer-share-leaves a)) (lot:armer-share-control-block a 0))) #xfffffffd))
      (check "wrong preimage fails"
             (not (spend (lambda (tx) (list (sig-for nil tx prevouts (first (lot:armer-share-leaves a)) armer) (random-preimage) (first (lot:armer-share-leaves a)) (lot:armer-share-control-block a 0))) #xfffffffd)))
      (check "recovery voters sweep after 144"
             (spend (lambda (tx) (let* ((leaf (second (lot:armer-share-leaves a))) (sorted (lot::sorted-keys voters))
                                        (sigs (mapcar (lambda (k) (let ((p (find k vprivs :key #'xonly-of :test #'equalp))) (and (member p (list (first vprivs) (second vprivs))) (sig-for nil tx prevouts leaf p)))) sorted)))
                                   (append (mapcar (lambda (s) (or s (u:octets))) (reverse sigs)) (list leaf (lot:armer-share-control-block a 1)))))
                    144))
      (check "sweep before 144 fails"
             (not (spend (lambda (tx) (let* ((leaf (second (lot:armer-share-leaves a))) (sorted (lot::sorted-keys voters))
                                             (sigs (mapcar (lambda (k) (let ((p (find k vprivs :key #'xonly-of :test #'equalp))) (and (member p (list (first vprivs) (second vprivs))) (sig-for nil tx prevouts leaf p)))) sorted)))
                                        (append (mapcar (lambda (s) (or s (u:octets))) (reverse sigs)) (list leaf (lot:armer-share-control-block a 1)))))
                         10))))
    (let ((outs (lot:forfeit-sweep-outputs 10000 (list (xonly-of 1) (xonly-of 2) (xonly-of 3)) 400)))
      (check-equal "sweep pays revealers pro rata (dust to fee)" (mapcar #'cdr outs) '(3200 3200 3200)))
    (check-signals "no revealers: no sweep (the slice waits for the re-arm round)" error (lot:forfeit-sweep-outputs 10000 nil 400))
    (check-equal "revealers are read back from a claim witness"
                 (lot:revealers-from-witness (list (u:octets 1 2) pre (make-array 40)) (list (cons (xonly-of armer) (lot:commitment-of pre))))
                 (list (xonly-of armer)))
    (check-equal "confiscation: punitive = everything to the lottery"
                 (lot:confiscation-outputs (hx "5120aa") 100000 500) (list (cons (hx "5120aa") 99500)))
    (check-equal "confiscation: respectful = obligations to lottery, change to operator p2wpkh"
                 (mapcar #'cdr (lot:confiscation-outputs (hx "5120aa") 100000 500 :respectful t :obligations-sats 40000 :operator-pubkey33 (up:compressed-pubkey 9)))
                 '(40000 59500))
    (check-equal "confiscation: respectful with dust change collapses to punitive"
                 (length (lot:confiscation-outputs (hx "5120aa") 40700 500 :respectful t :obligations-sats 40000 :operator-pubkey33 (up:compressed-pubkey 9)))
                 1)))

(with-gate ("reserves: the reference's pinned cltv-offset-v2 seven-voter script")
  ;; deposits-core CLTV_OFFSET_V2_SEVEN_VOTERS_HEX: operator key [1;32], members [2..7;32],
  ;; quorum_expiry 800000, ledger hash [0x5a;32], signet.  Tier 1 is ceil(7/2) - 1 = 3 of 7.
  (let* ((key (lambda (i) (up:compressed-pubkey (u:be->int (make-array 32 :element-type '(unsigned-byte 8) :initial-element i)))))
         (r (rs:build-reserves :operator (funcall key 1) :members (loop for i from 2 to 7 collect (funcall key i))
                               :ledger-hash (make-array 32 :element-type '(unsigned-byte 8) :initial-element #x5a)
                               :quorum-expiry 800000 :ruleset "cltv-offset-v2" :network :signet)))
    (format t "~&  CL_SEVEN_VOTERS_HEX=~a~%" (u:bytes->hex (rs:reserves-spk r)))
    (check-equal "tier 1 is 3 of 7" (rs:tier-threshold (second (rs:reserves-tiers r))) 3)
    (check-bytes "scriptPubKey matches CLTV_OFFSET_V2_SEVEN_VOTERS_HEX" (rs:reserves-spk r)
                 (hx "51206e92587c6bcdf7bd653c242c1937224eac71bc486fe7c3b9fc6edb70b129dbeb"))))



(with-gate ("lottery: byte-for-byte against the reference builder")
  ;; inspect/vectors/lottery_subsets.txt: deposits-core's tests/lottery_subset_vector.rs
  ;; for keys from secrets [i;32], commitments [i;20], voters 21..23 (2-of-3), signet.
  (let* ((lines (with-open-file (in (vector-path "lottery_subsets.txt"))
                  (loop for l = (read-line in nil) while l collect l)))
         (vec (lambda (key) (let ((pfx (format nil "VEC ~a=" key)))
                              (let ((l (find pfx lines :test (lambda (p l) (and (>= (length l) (length p)) (string= p (subseq l 0 (length p))))))))
                                (and l (subseq l (length pfx)))))))
         (seed-priv (lambda (i) (u:be->int (make-array 32 :element-type '(unsigned-byte 8) :initial-element i))))
         (voters (mapcar (lambda (i) (xonly-of (funcall seed-priv i))) '(21 22 23)))
         (name (lambda (idx) (format nil "~{~a~^,~}" idx))))
    (dolist (k '(1 2 3 7))
      (let* ((parts (loop for i from 1 to k collect (lot:make-participant :pubkey (xonly-of (funcall seed-priv i))
                                                                            :commitment (make-array 20 :element-type '(unsigned-byte 8) :initial-element i)
                                                                            :target (format nil "tb1p~a" i))))
             (l (lot:build-lottery parts voters 2 :network :signet))
             (subsets (lot:lottery-subsets l)) (n (length subsets)))
        (check-equal (format nil "k=~a full-set leaf" k) (u:bytes->hex (first (lot:lottery-leaves l))) (funcall vec (format nil "k=~a full" k)))
        (check-equal (format nil "k=~a lottery address" k) (lot:lottery-address l) (funcall vec (format nil "k=~a address" k)))
        (check-equal (format nil "k=~a control block of the full-set leaf" k) (u:bytes->hex (lot:lottery-control-block l 0)) (funcall vec (format nil "k=~a control_full" k)))
        (check-equal (format nil "k=~a recovery leaf (CSV 144)" k) (u:bytes->hex (nth (lot::recovery-leaf-index l 0) (lot:lottery-leaves l))) (funcall vec (format nil "k=~a recovery144" k)))
        (check-equal (format nil "k=~a subset count" k) (princ-to-string n) (funcall vec (format nil "k=~a subsets" k)))
        (dolist (pos (remove-duplicates (list 0 (floor n 2) (max 0 (1- n)))))
          (when (< pos n)
            (let* ((idx (nth pos subsets)) (i (lot:subset-leaf-index l idx)))
              (check-equal (format nil "k=~a subset [~a] leaf" k (funcall name idx)) (u:bytes->hex (nth i (lot:lottery-leaves l)))
                           (funcall vec (format nil "k=~a subset[~a]" k (funcall name idx))))
              (check-equal (format nil "k=~a subset [~a] control block" k (funcall name idx)) (u:bytes->hex (lot:lottery-control-block l i))
                           (funcall vec (format nil "k=~a control[~a]" k (funcall name idx)))))))))
    (dolist (c '(((0 1 2 3 4 5 6) (17 76 40 23 61 18 50)) ((0 2 5) (20 76 33)) ((1 3 4 6) (76 76 76 76)) ((4) (29)) ((0 1 2 3 5 6) (17 18 19 20 21 22))))
      (destructuring-bind (idx lens) c
        (check-equal (format nil "winner over [~a]" (funcall name idx))
                     (princ-to-string (lot:subset-winner idx (mapcar (lambda (n) (make-array n :element-type '(unsigned-byte 8) :initial-element 0)) lens)))
                     (funcall vec (format nil "winner[~a](~a)" (funcall name idx) (funcall name lens))))))
    (dotimes (i 4)
      (check-equal (format nil "derived preimage ~a" i) (u:bytes->hex (lot:derive-preimage (u:sha256 (u:int->be i 4)))) (funcall vec (format nil "preimage[~a]" i))))
    (check-equal "armer share address"
                 (lot:armer-share-address (lot:build-armer-share (xonly-of (funcall seed-priv 1)) (make-array 20 :element-type '(unsigned-byte 8) :initial-element 1) voters 2 :network :signet))
                 (funcall vec "armer_share"))
    ;; The unsigned claim (DEP-03), legacy serialization as the reference pins it.
    (let ((fill (lambda (b) (make-array 32 :element-type '(unsigned-byte 8) :initial-element b)))
          (dest (u:cat (u:octets #x51 #x20) (xonly-of (funcall seed-priv 1)))))
      (loop for (name subset coll) in (list (list "claim_full" nil (list (funcall fill #x33) 1 600000))
                                            (list "claim_subset" t (list (funcall fill #x33) 1 600000))
                                            (list "claim_sole_no_collateral" nil nil))
            do (let ((tx (lot:claim-tx (funcall fill #x22) 0 1000000 coll dest :subset subset)))
                 (check-equal (format nil "~a tx" name)
                              (u:bytes->hex (btx:serialize-tx (btx:make-tx :version 2 :locktime 0 :segwit-p nil :inputs (btx:tx-inputs tx)
                                                                           :outputs (btx:tx-outputs tx) :witnesses nil)))
                              (funcall vec name)))))))

(with-gate ("lottery: the unsigned confiscation, byte for byte against the reference")
  ;; inspect/vectors/confiscation_tx.txt: deposits-node's confiscation_tx_vector_is_pinned.
  (let* ((lines (with-open-file (in (vector-path "confiscation_tx.txt")) (loop for l = (read-line in nil) while l collect l)))
         (vec (lambda (key) (let ((pfx (format nil "VEC ~a=" key)))
                              (let ((l (find-if (lambda (l) (and (>= (length l) (length pfx)) (string= pfx (subseq l 0 (length pfx))))) lines)))
                                (and l (subseq l (length pfx)))))))
         (seed-priv (lambda (i) (u:be->int (make-array 32 :element-type '(unsigned-byte 8) :initial-element i))))
         (voters (mapcar (lambda (i) (xonly-of (funcall seed-priv i))) '(21 22 23)))
         (parts (loop for i from 1 to 3 collect (lot:make-participant :pubkey (xonly-of (funcall seed-priv i))
                                                                       :commitment (make-array 20 :element-type '(unsigned-byte 8) :initial-element i)
                                                                       :target (format nil "tb1p~a" i))))
         (l (lot:build-lottery parts voters 2 :network :signet))
         (fee (lot:confiscation-fee 8))
         (operator (up:compressed-pubkey (funcall seed-priv 9))))
    (check-equal "DEP-03 fee for 8 voters" (princ-to-string fee) (funcall vec "fee"))
    (loop for (name respectful locktime) in '(("punitive" nil 0) ("respectful" t 1234))
          do (let* ((outs (lot:confiscation-outputs (lot:lottery-spk l) 50000000 fee :respectful respectful
                                                    :obligations-sats 10000000 :operator-pubkey33 operator))
                    (tx (btx:make-tx :version 2 :locktime locktime :segwit-p nil
                                     :inputs (list (btx:make-txin :prev-hash (make-array 32 :element-type '(unsigned-byte 8) :initial-element #x11)
                                                                  :prev-index 1 :script (u:octets) :sequence #xfffffffd))
                                     :outputs (loop for (spk . v) in outs collect (btx:make-txout :value v :script spk))
                                     :witnesses nil)))
               (check-equal (format nil "~a confiscation tx" name) (u:bytes->hex (btx:serialize-tx tx)) (funcall vec name))))))

(with-gate ("ledger: the DEP-05 collateral floor against the shared vector")
  (let ((v (com.inuoe.jzon:parse (uiop:read-file-string (vector-path "collateral_floor.json")))))
    (loop for case across (gethash "cases" v)
          do (let* ((members (map 'list (lambda (b) (lg::make-quorum-member :min-collateral-bps (and (integerp b) b)))
                                  (gethash "member_bps" case)))
                    (floor (lg:collateral-floor-bps members)))
               (check-equal (format nil "~a: floor" (gethash "name" case)) floor (gethash "floor_bps" case))
               (check-equal (format nil "~a: verdict" (gethash "name" case))
                            (lg:collateral-meets-floor-p (gethash "reserves" case) (gethash "collateral" case) floor)
                            (gethash "ok" case))))))

;;; inspect/vectors/armer_eligibility.json: the DEP-03 replacement-collateral cut,
;;; shared with deposits-rust (deposits-node/tests/vectors/armer_eligibility.json).
(with-gate ("lottery: armer eligibility cut against the shared vector")
  (let ((v (com.inuoe.jzon:parse (uiop:read-file-string (vector-path "armer_eligibility.json")))))
    (loop for case across (gethash "cases" v)
          do (let ((facts (make-hash-table :test #'equalp)) (names (make-hash-table :test #'equalp)) (armers '()))
               (loop for a across (gethash "armers" case) for i from 1
                     for pk = (let ((b (make-array 33 :element-type '(unsigned-byte 8) :initial-element i))) (setf (aref b 0) 2) b)
                     for p = (gethash "pledge" a)
                     for txid = (make-array 32 :element-type '(unsigned-byte 8) :initial-element i)
                     for num = (lambda (k h) (let ((x (gethash k h))) (and (integerp x) x)))
                     do (setf (gethash pk names) (gethash "id" a))
                        (when (hash-table-p p)
                          (setf (gethash txid facts) (list (funcall num "created" p) (funcall num "value" p) (funcall num "spent_at" p))))
                        (push (list pk (make-array 20 :element-type '(unsigned-byte 8) :initial-element i) "t"
                                    (and (hash-table-p p) (list txid 0 (gethash "declared" a)))
                                    (gethash "arm_height" a) 1)
                              armers))
               (let ((pledge-fn (lambda (txid vout scan-from)
                                  (declare (ignore vout))
                                  (destructuring-bind (&optional created value spent) (gethash txid facts)
                                    (list :created created :value-sats value
                                          :spend (cond ((null spent) :unspent) ((>= spent scan-from) (list :at spent)) (t :before)))))))
                 (multiple-value-bind (in out snapshot)
                     (nd:split-armers armers (gethash "required_sats" case) pledge-fn)
                   (declare (ignore out))
                   (check-equal (format nil "~a: participants" (gethash "name" case))
                                (sort (mapcar (lambda (a) (gethash (first a) names)) in) #'string<)
                                (coerce (gethash "participants" (gethash "expect" case)) 'list))
                   (check-equal (format nil "~a: snapshot" (gethash "name" case)) snapshot (gethash "snapshot" (gethash "expect" case)))))))))

;;; inspect/vectors/cosign_refusal.json: DEP-05 "Deposed operator", shared with deposits-rust
;;; (deposits-node/tests/vectors/cosign_refusal.json).
(with-gate ("DEP-05 deposed operator: cosign refusal against the shared vector")
  (let ((v (com.inuoe.jzon:parse (uiop:read-file-string (vector-path "cosign_refusal.json")))))
    (check "the vector has cases" (>= (length (gethash "cases" v)) 10))
    (loop for c across (gethash "cases" v)
          for members = (loop for i below (gethash "members" c) collect (format nil "m~a" i))
          for disputes = (loop for d across (gethash "disputes" c)
                               collect (list :by (gethash "by" d) :last-valid (gethash "last_valid_sequence" d)
                                             :reason (gethash "reason" d) :acquired (gethash "acquired" d)))
          do (check-equal (gethash "name" c)
                          (and (cl-deposits.node::cosign-refusal "m0" members (gethash "latest_quorum_begin_seq" c) disputes) t)
                          (gethash "refuse" c)))))

;;; inspect/vectors/rotation_tx.txt: DEP-03 "Rotation transaction", shared with deposits-rust
;;; (deposits-core/tests/vectors/rotation_tx.txt).  Txids there are display (reversed) hex.
(with-gate ("DEP-03 rotation transaction: byte for byte against the shared vector")
  (let ((cases '()) (cur nil))
    (with-open-file (in (vector-path "rotation_tx.txt"))
      (loop for line = (read-line in nil) while line
            for words = (uiop:split-string line :separator " ")
            for key = (first words)
            do (cond ((or (zerop (length line)) (char= (char line 0) #\#)))
                     ((string= key "case") (setf cur (list :name (second words) :extras '())) (push cur cases))
                     (t (let ((outpoint (lambda (s) (let ((c (position #\: s)))
                                                      (list (reverse (u:hex->bytes (subseq s 0 c))) (parse-integer s :start (1+ c)))))))
                          (cond ((string= key "vault") (setf (getf (car cases) :vault) (append (funcall outpoint (second words)) (list (parse-integer (third words))))))
                                ((string= key "splice") (setf (getf (car cases) :splice) (append (funcall outpoint (second words)) (list (parse-integer (third words))))))
                                ((string= key "out") (setf (getf (car cases) :extras) (append (getf (car cases) :extras) (list (cons (u:hex->bytes (second words)) (parse-integer (third words)))))))
                                ((string= key "new_vault_spk") (setf (getf (car cases) :spk) (u:hex->bytes (second words))))
                                ((string= key "tx") (setf (getf (car cases) :tx) (second words)))
                                (t (setf (getf (car cases) (intern (string-upcase key) :keyword)) (parse-integer (second words))))))))))
    (check-equal "four shapes" (length cases) 4)
    (dolist (c (reverse cases))
      (destructuring-bind (txid vout sats) (getf c :vault)
        (let ((tx (cl-deposits.rotation:build-rotation :vault-txid txid :vault-vout vout :vault-sats sats
                                                       :voters (getf c :voters) :feerate (getf c :feerate) :locktime (getf c :locktime)
                                                       :new-vault-spk (getf c :spk) :splice (getf c :splice) :extras (getf c :extras))))
          (check-equal (format nil "~a rotation tx" (getf c :name))
                       (and tx (u:bytes->hex (btx:serialize-tx tx :witness nil))) (getf c :tx)))))
    (check "a rotation leaving the vault below dust is refused"
           (null (cl-deposits.rotation:build-rotation :vault-txid (make-array 32 :element-type '(unsigned-byte 8) :initial-element 1)
                                                      :vault-vout 0 :vault-sats 900 :voters 8
                                                      :new-vault-spk (make-array 34 :element-type '(unsigned-byte 8) :initial-element 0))))))

(report)
