;;;; inspect/node-test.lisp — four nodes and two wallets on one in-process bus:
;;;; quorum formation, QuorumBegin, deposits, a hash-locked transfer; every
;;;; published update re-verified with the same code that verified the fixture.

(in-package #:cl-deposits.test)

(defvar *height* 1000)

(with-gate ("nodes: quorum formation over the bus")
  (let* ((bus (bus:make-mock-bus))
         (hf (lambda () *height*))
         (mock-ln (ln:make-mock-ln))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf :ln mock-ln))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a" :reserves 15600000 :collateral 23400000))
         (lb (nd:open-ledger b :reserves-id "genesis:b")) (lc (nd:open-ledger c :reserves-id "genesis:c"))
         (ld (nd:open-ledger d :reserves-id "genesis:d")))
    (check "even-y protocol keys" (every (lambda (n) (= 2 (aref (nd:node-pubkey n) 0))) (list a b c d)))
    (check-equal "genesis applied" (lg:ledger-sequence (nd:record-ledger la)) 0)
    (dolist (m (list b c d)) (nd:add-member a la (nd:node-pubkey m)))
    (check-equal "three QuorumAddMember on A" (lg:ledger-sequence (nd:record-ledger la)) 3)
    (check-equal "three staged members" (length (lg:ledger-next-quorum-members (nd:record-ledger la))) 3)
    (check "each member recorded QuorumJoin on its own ledger"
           (every (lambda (rec) (and (= 1 (lg:ledger-sequence (nd:record-ledger rec)))
                                     (= 1 (length (lg:ledger-joined-quorums (nd:record-ledger rec))))))
                  (list lb lc ld)))
    (check "members replicate A's ledger at the same tip"
           (every (lambda (n) (let ((r (nd:find-record n (nd:record-id-hex la))))
                                (and r (not (nd:record-owned-p r))
                                     (equalp (lg:ledger-chain-tip (nd:record-ledger r)) (lg:ledger-chain-tip (nd:record-ledger la))))))
                  (list b c d)))
    ;; QuorumBegin: cosigned by a majority of the STAGED set.
    (multiple-value-bind (qb reserves)
        (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d")) :funding-vout 0
                              :amount-msats 15600000 :collateral-msats 23400000)
      (check "QuorumBegin carries >= 2 of 3 staged cosignatures" (>= (length (up:update-cosignatures qb)) 2))
      (check "quorum_expiry does not exceed any member's commitment"
             (<= (rs::reserves-quorum-expiry reserves)
                 (reduce #'min (mapcar #'lg:member-membership-until (lg:ledger-quorum-members (nd:record-ledger la))))))
      (check "reserves address is signet taproot" (string= "tb1p" (subseq (rs:reserves-address reserves) 0 4)))
      (check-equal "ledger quorum active with 3 members"
                   (list (lg:ledger-quorum-state (nd:record-ledger la)) (length (lg:ledger-quorum-members (nd:record-ledger la))))
                   '(:active 3))
      (check-bytes "reserves commit to the pre-QuorumBegin chain hash" (rs:reserves-ledger-hash reserves) (up:update-prev-hash qb))
      (check-signals "a Q=2 QuorumBegin is refused by the fold" lg:ledger-error
        (lg:apply-operation (lg:make-ledger)
                            (list :type :quorum-begin :reserves-id "x" :spending-txid (u:sha256 (hx "01")) :new-outpoint-txid (u:sha256 (hx "01"))
                                  :new-outpoint-vout 0 :amount 1 :quorum-expiry 1 :ledger-hash (u:sha256 (hx "02"))
                                  :quorum-members (list (nd:node-pubkey b) (nd:node-pubkey c)) :collateral-amount 0))))
    ;; Deposits and a transfer.
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus))
           (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (id (nd:record-id-hex la))
           (d1 (nd:wallet-open-deposit w1 id)) (d2 (nd:wallet-open-deposit w2 id)))
      (check-equal "deposit ids derive from pk() descriptors"
                   (list d1 d2) (list (op:deposit-id (format nil "pk(~a)" (u:bytes->hex (nd:wallet-pubkey w1))))
                                      (op:deposit-id (format nil "pk(~a)" (u:bytes->hex (nd:wallet-pubkey w2))))))
      (nd:credit-onchain a la d1 100000 :txid (u:sha256 (hx "c0ffee")))
      (check-equal "balance after credit" (nd:wallet-balance w1 id d1) 100000)
      (multiple-value-bind (tid preimage) (nd:wallet-transfer w1 id d1 d2 40000 :height *height*)
        (check-equal "locked after TransferLock" (multiple-value-list (nd:wallet-balance w1 id d1)) '(100000 40000))
        (check "TransferComplete with the preimage" (nd:wallet-complete-transfer w1 id tid preimage))
        (check-equal "balances settle 60000 / 40000"
                     (list (nd:wallet-balance w1 id d1) (nd:wallet-balance w2 id d2)) '(60000 40000)))
      ;; Lightning: an invoice, cosigned attestation, payment, InvoiceCredit.
      (multiple-value-bind (bolt11 hash res) (nd:wallet-make-invoice w2 id d2 25000 :operator-pubkey (nd:node-pubkey a))
        (check "invoice minted by the (mock) Lightning node" (string= "lnmock1" (subseq bolt11 0 7)))
        (check "attestation cosigned by a quorum member" (and (w:jget res "cosign_signature") t))
        (check-equal "nothing credited before payment" (nd:credit-paid-invoices a) '())
        (ln:mock-ln-settle mock-ln hash)
        (check-equal "payment settled -> one InvoiceCredit" (nd:credit-paid-invoices a) (list hash))
        (check-equal "w2 balance includes the credit" (nd:wallet-balance w2 id d2) 65000)
        (check "InvoiceCredit carries the bolt11-derived invoice id"
               (let ((o (op:decode-operation (up:update-message (first (nd:record-history la))))))
                 (and (eq (op:operation-type o) :invoice-credit)
                      (string= (op:field o :invoice-id) (format nil "bolt11:~a" (subseq bolt11 0 32))))))
        (check-signals "the same payment cannot be credited twice" lg:ledger-error
          (lg:apply-operation (nd:record-ledger la)
                              (list :type :invoice-credit :payment-hash hash :deposit-id d2 :amount 1 :invoice-id "x" :sequence-number 99)))
        (check-signals "an invoice beyond reserves is refused" nd:node-error
          (nd:wallet-make-invoice w2 id d2 (* 2 (lg:ledger-reserves-amount (nd:record-ledger la))))))
      ;; Rejections.
      (check-signals "transfer signed by the wrong wallet is refused" nd:node-error
        (nd:wallet-transfer w2 id d1 d2 1000 :height *height*))
      (check-signals "insufficient balance is refused" nd:node-error
        (nd:wallet-transfer w1 id d1 d2 999999 :height *height*))
      (let ((forged (nd:make-wallet :priv 55555555555555555555 :bus bus)))  ; same key, stale nonce counter
        (check-signals "replayed nonce is refused" nd:node-error
          (nd:wallet-transfer forged id d1 d2 1000 :height *height*)))
      ;; Replicas agree, and everything published re-verifies from scratch.
      (check "all replicas at A's tip"
             (every (lambda (n) (equalp (lg:ledger-chain-tip (nd:record-ledger (nd:find-record n id)))
                                        (lg:ledger-chain-tip (nd:record-ledger la))))
                    (list b c d)))
      (let* ((events (bus:bus-fetch bus (cl-nostr.filter:make-filter :kinds (list w:+kind-update+) :tags (list (cons "d" (list (w:ledger-tag (u:hex->bytes id))))))))
             (updates (mapcar #'w:event->update events))
             (fresh (lg:make-ledger)) (members (mapcar #'lg:member-pubkey (lg:ledger-quorum-members (nd:record-ledger la)))))
        (check-equal "published updates cover the whole chain" (mapcar #'up:update-seq updates)
                     (loop for i to (lg:ledger-sequence (nd:record-ledger la)) collect i))
        (check "every Nostr event signature valid" (every #'cl-nostr.event:valid-event-p events))
        (check "every operator signature verifies (v1)" (every (lambda (u) (eq :v1 (up:verify-operator-signature u))) updates))
        (check "every post-QuorumBegin update has a member majority"
               (loop for u in updates
                     for o = (op:decode-operation (up:update-message u))
                     for after = nil then (or after (eq (op:operation-type (op:decode-operation (up:update-message (nth (1- (up:update-seq u)) updates)))) :quorum-begin))
                     always (or (not after) (up:verify-cosignatures u :quorum members :threshold 2))))
        (check "member_ledger_hash is each member's own tip content hash"
               (every (lambda (cs) (let ((n (find (up:cosig-pubkey cs) (list b c d) :key #'nd:node-pubkey :test #'equalp)))
                                    (equalp (up:cosig-member-ledger-hash cs)
                                            (up:content-hash (first (nd:record-history (nd:own-ledger n)))))))
                      (up:update-cosignatures (car (last updates)))))
        (dolist (u updates) (lg:apply-update fresh u))
        (check-bytes "fold of published updates reaches A's tip" (lg:ledger-chain-tip fresh) (lg:ledger-chain-tip (nd:record-ledger la)))
        (check-equal "obligations from the fold" (lg:total-obligations fresh) 125000))
      ;; Persistence round trip in the fixture format.
      (let* ((dir (format nil "/tmp/cl-deposits-test-~a/" (random 1000000)))
             (path (progn (setf (nd::node-data-dir a) dir) (nd:save-record a la)
                          (merge-pathnames (format nil "ledger_~a.json" (subseq id 0 16)) dir)))
             (bus2 (bus:make-mock-bus))
             (a2 (nd:make-node :priv 11111111111111111111 :bus bus2 :height-fn hf))
             (x (nd:make-node :priv 77777777777777777777 :bus bus2 :height-fn hf))
             (ra (nd:load-record a2 path :owned-p t))
             (rx (nd:load-record x path)))
        (check-bytes "reloaded owner at the same tip" (lg:ledger-chain-tip (nd:record-ledger ra)) (lg:ledger-chain-tip (nd:record-ledger la)))
        (check-bytes "stranger validates the file as a replica" (lg:ledger-chain-tip (nd:record-ledger rx)) (lg:ledger-chain-tip (nd:record-ledger la)))
        (check-equal "reloaded owner continues the chain (needs cosigs; none reachable -> fails cleanly)"
                     (handler-case (progn (nd:credit-onchain a2 ra d1 1 :txid (u:sha256 (hx "01"))) :committed)
                       (nd:node-error () :refused))
                     :refused)))
    (format t "      A log: ~{~a~^ | ~}~%" (reverse (nd:node-log a)))
    (format t "      B log: ~{~a~^ | ~}~%" (reverse (nd:node-log b)))))



(with-gate ("disputes: fraud proof, forks, confiscation, lottery, custody transfer")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a2" :reserves 15600000 :collateral 23400000))
         (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m))))
    (dolist (m (list b c d)) (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d2")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (d1 (nd:wallet-open-deposit w1 id)))
      (nd:credit-onchain a la d1 100000 :txid (u:sha256 (hx "c0ffee2")))
      ;; --- The operator equivocates: two different updates at the same sequence.
      (let* ((seq (1+ (lg:ledger-sequence (nd:record-ledger la))))
             (mk (lambda (amount)
                   (let ((u (up:make-signed-update :operator-id (nd:node-pubkey a) :ledger-id (u:hex->bytes id) :seq seq
                                                   :prev-hash (lg:ledger-chain-tip (nd:record-ledger la))
                                                   :message (op:encode-operation (list :type :onchain-credit :txid (u:sha256 (hx "ee")) :vout 0
                                                                                       :deposit-id d1 :amount amount :funding-address "x")))))
                     (up:sign-operator u (nd::node-priv a)) u)))
             (u1 (funcall mk 1)) (u2 (funcall mk 2))
             (proof (fr:make-equivocation-proof (nd:node-pubkey a) (u:hex->bytes id) u1 u2)))
        (check "equivocation proof verifies" (fr:verify-equivocation proof))
        (check "a same-content pair is not an equivocation" (not (fr:verify-equivocation (fr:make-equivocation-proof (nd:node-pubkey a) (u:hex->bytes id) u1 u1))))
        (check-bytes "proof hash survives the JSON round trip" (fr:proof-hash (fr:json->proof (fr:proof->json proof))) (fr:proof-hash proof))
        (check-equal "proof discriminant" (fr:proof-discriminant :equivocation) 8)
        ;; A non-conforming update: crediting beyond... (a DepositClose on a funded deposit)
        (let ((bad (let ((u (up:make-signed-update :operator-id (nd:node-pubkey a) :ledger-id (u:hex->bytes id) :seq seq
                                                   :prev-hash (lg:ledger-chain-tip (nd:record-ledger la))
                                                   :message (op:encode-operation (list :type :deposit-close :deposit-id d1)))))
                     (up:sign-operator u (nd::node-priv a)) u)))
          (check "non-conforming update proof verifies against the canonical history"
                 (fr:verify-non-conforming-update (fr:make-non-conforming-update-proof (nd:node-pubkey a) (u:hex->bytes id) bad)
                                                  (reverse (nd:record-history la))))
          (check "a conforming update is not a valid proof"
                 (not (fr:verify-non-conforming-update (fr:make-non-conforming-update-proof (nd:node-pubkey a) (u:hex->bytes id) u1)
                                                       (reverse (nd:record-history la))))))
        ;; --- Broadcast the proof: every member verifies it and forks.
        (nd:broadcast-fraud b proof)
        (check "all three members opened dispute forks"
               (every (lambda (m) (nd:find-fork m id (nd:node-pubkey m))) (list b c d)))
        (check "members replicate each other's forks"
               (every (lambda (m) (= 3 (length (nd:forks-of m id)))) (list b c d)))
        (check-equal "fork state is disputed" (lg:ledger-dispute-state (nd:record-ledger (nd:find-fork b id (nd:node-pubkey b)))) :disputed)
        ;; --- Arm.
        (dolist (m (list b c d)) (nd:arm-dispute m (nd:find-fork m id (nd:node-pubkey m))))
        (check-equal "three armers visible to everyone" (mapcar (lambda (m) (length (nd:armers-of m id))) (list b c d)) '(3 3 3))
        ;; --- Confiscation, built by b, signed by the recovery quorum over the relay.
        (multiple-value-bind (ctx lottery)
            (handler-case (nd:confiscate b id)
              (error (e) (format t "      confiscate failed: ~a~%      c log: ~{~a~^ | ~}~%      d log: ~{~a~^ | ~}~%" e (reverse (nd:node-log c)) (reverse (nd:node-log d))) (error e)))
          (check "confiscation spends the reserves via tier 0 (verified under consensus)" (and ctx t))
          (check-equal "punitive: one output, to the lottery" (length (btx:tx-outputs ctx)) 1)
          (check "lottery output pays the lottery script" (equalp (btx:txout-script (first (btx:tx-outputs ctx))) (lot:lottery-spk lottery)))
          (check "other members rebuilt the same lottery" (every (lambda (m) (let ((f (nd:find-fork m id (nd:node-pubkey m)))) (and (nd:record-lottery f) (equalp (lot:lottery-spk (nd:record-lottery f)) (lot:lottery-spk lottery))))) (list c d)))
          (check "signers kept the unsigned confiscation (same txid as the broadcast one)"
                 (every (lambda (m) (equalp (btx:tx-txid (nd:record-confiscation (nd:find-fork m id (nd:node-pubkey m)))) (btx:tx-txid ctx))) (list c d)))
          ;; --- Reveal.
          (dolist (m (list b c d)) (nd:publish-reveal m id))
          (check-equal "every member holds all three reveals" (mapcar (lambda (m) (length (nd:reveals-of m id))) (list b c d)) '(3 3 3))
          ;; --- Claim or yield.
          (let ((outcomes (mapcar (lambda (m) (multiple-value-list (nd:claim-or-yield m id))) (list b c d))))
            (check-equal "exactly one winner" (count :won outcomes :key #'first) 1)
            (check-equal "two yields" (count :yielded outcomes :key #'first) 2)
            (let* ((winner (nth (position :won outcomes :key #'first) (list b c d)))
                   (claim (second (find :won outcomes :key #'first)))
                   (wfork (nd:find-fork winner id (nd:node-pubkey winner))))
              (check "winner is the script-selected participant"
                     (equalp (up:x-only (nd:node-pubkey winner))
                             (lot:participant-pubkey (nth (lot:calculate-winner (mapcar (lambda (p) (cdr (find (lot:participant-pubkey p) (nd:reveals-of b id) :key (lambda (r) (up:x-only (car r))) :test #'equalp))) (lot:lottery-participants lottery))) (lot:lottery-participants lottery)))))
              (check "claim tx spends the lottery output (verified under consensus)" (equalp (btx:txin-prev-hash (first (btx:tx-inputs claim))) (btx:tx-txid ctx)))
              (check-equal "winner's fork: DisputeAcquire, custody transferred"
                           (list (lg:ledger-dispute-state (nd:record-ledger wfork)) (equalp (lg:ledger-operator-key (nd:record-ledger wfork)) (nd:node-pubkey winner)))
                           '(:normal t))
              (check "losers' forks tombstoned"
                     (every (lambda (m) (or (eq m winner) (eq :tombstoned (lg:ledger-dispute-state (nd:record-ledger (nd:find-fork m id (nd:node-pubkey m))))))) (list b c d)))
              (check "everyone replicates the winner's DisputeAcquire"
                     (every (lambda (m) (let ((f (nd:find-fork m id (nd:node-pubkey winner)))) (and f (equalp (lg:ledger-operator-key (nd:record-ledger f)) (nd:node-pubkey winner))))) (list b c d))))))))))



(with-gate ("messaging: delivery escalation (DEP-12) and couriers (DEP-13)")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (e (nd:make-node :priv 99999999999999999999 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (kn (nd:make-node :priv 77777777777777777777 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a3" :reserves 15600000 :collateral 23400000))
         (le (nd:open-ledger e :reserves-id "genesis:e3" :reserves 15600000 :collateral 23400000))
         (ida (nd:record-id-hex la)) (ide (nd:record-id-hex le)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m))))
    (dolist (opnode (list a e))
      (let ((rec (if (eq opnode a) la le)))
        (dolist (m (list b c d)) (nd:add-member opnode rec (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
        (nd:begin-quorum opnode rec :funding-txid (u:sha256 (u:cat (hx "f00d") (nd:node-pubkey opnode))) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)))
    ;; Wallets: w1 on A, w2 on E; courier deposits on both, funded by the operators.
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (kwa (nd:make-wallet :priv 77777777777777777777 :bus bus)) (kwe (nd:make-wallet :priv 77777777777777777777 :bus bus))
           (d1 (nd:wallet-open-deposit w1 ida)) (d2 (nd:wallet-open-deposit w2 ide))
           (ka (nd:wallet-open-deposit kwa ida)) (ke (nd:wallet-open-deposit kwe ide)))
      (nd:credit-onchain a la d1 500000 :txid (u:sha256 (hx "01")))
      (nd:credit-onchain e le ke 800000 :txid (u:sha256 (hx "02")))
      ;; --- DEP-12: A ignores w1's transfer; w1 escalates through member b.
      (setf (nd:node-ignore-actions a) '("transfer_lock"))
      (let* ((params (w:json-object "operation" "AAAA"))   ; content of the ignored request (any signed request)
             (h (nd:wallet-request-hash w1 ida "transfer_lock" params)))
        (multiple-value-bind (ok res err rh) (nd:wallet-request w1 ida "transfer_lock" params :timeout 1)
          (declare (ignore res))
          (check "operator silently ignored the request" (and (not ok) (string= err "timeout")))
          (check-bytes "request hash = sha256(content)" rh h))
        (let* ((lb (nd:own-ledger b))
               (reply (nd:wallet-escalate w1 (nd:record-id-hex lb) h ida (nd:node-pubkey-hex a)))
               (embed (first (nd:record-history lb))))
          (check-equal "member anchored a DeliveryEmbed on its ledger" (op:operation-type (op:decode-operation (up:update-message embed))) :delivery-embed)
          (check-equal "reply carries the embed sequence" (w:jget reply "sequence") (up:update-seq embed))
          ;; No causal link yet: b has not cosigned on A since the embed.
          (check-equal "no proof before the member cosigns again"
                       (nth-value 1 (fr:verify-censorship (w:json params) embed (reverse (nd:record-history lb)) (reverse (nd:record-history la))))
                       "no causal link: the member has not cosigned past the embed")
          ;; A keeps operating (b cosigns, carrying its post-embed ledger hash) and time passes.
          (setf (nd:node-ignore-actions a) '())
          (nd:credit-onchain a la d1 1 :txid (u:sha256 (hx "03")))
          (check-equal "deadline not reached yet"
                       (nth-value 1 (fr:verify-censorship (w:json params) embed (reverse (nd:record-history lb)) (reverse (nd:record-history la))))
                       "deadline not reached")
          (let ((*height* (+ *height* 100)))
            (nd:credit-onchain a la d1 1 :txid (u:sha256 (hx "04")))
            (check "past the service deadline with no answer: censorship proven"
                   (fr:verify-censorship (w:json params) embed (reverse (nd:record-history lb)) (reverse (nd:record-history la))
                                         :processed-p (lambda (o) (eq (op:operation-type o) :transfer-lock))))
            (check "not censorship if the operator answered"
                   (not (fr:verify-censorship (w:json params) embed (reverse (nd:record-history lb)) (reverse (nd:record-history la))
                                              :processed-p (lambda (o) (eq (op:operation-type o) :onchain-credit))))))))
      ;; --- DEP-13: w1 (ledger A) pays w2 (ledger E) through courier k.
      (let ((k (cr:make-courier kn)))
        (cr:courier-serve k ida ka kwa) (cr:courier-serve k ide ke kwe)
        (cr:advertise-courier k)
        (let ((ad (cr:courier-advertisement k)))
          (check-equal "advertisement lists both ledgers" (length (w:jget ad "ledgers")) 2)
          (check-equal "courier liquidity on E" (cr::courier-balance k ide) 800000))
        (check-equal "route fee = fee_out(A) + fee_in(E)" (cr:route-fee k ida ide 100000) (+ 100 300 100 100))
        (multiple-value-bind (leg1 preimage forward) (cr:wallet-route w1 (nd:node-pubkey-hex kn) ida ide d1 d2 100000 :height *height*)
          (check-equal "forward amount = amount - fee" forward (- 100000 600))
          (check-equal "leg 1 locked on A" (multiple-value-list (nd:wallet-balance w1 ida d1)) '(500002 100000))
          ;; The courier saw leg 1 and locked leg 2 on E.
          (let ((leg2 (nd:wallet-pending-lock kn ide (u:sha256 preimage) d2)))
            (check "courier locked leg 2 to w2 on E behind the same hash" (and leg2 t))
            (check-equal "leg 2 amount is the forward amount" (getf leg2 :amount) forward)
            (check "leg 2 times out before leg 1" (< (getf leg2 :timeout-height) (+ *height* 144)))
            ;; w2 claims leg 2 with the preimage; the courier completes leg 1.
            (check "w2 completes leg 2" (nd:wallet-complete-transfer w2 ide (getf leg2 :transfer-id) preimage))
            (check-equal "w2 received the forward amount" (nd:wallet-balance w2 ide d2) forward)
            (check-equal "courier collected leg 1 on A" (nd:wallet-balance kwa ida ka) 100000)
            (check-equal "w1 paid the full amount" (multiple-value-list (nd:wallet-balance w1 ida d1)) '(400002 0))
            (check-equal "courier's E balance fell by the forward amount" (nd:wallet-balance kwe ide ke) (- 800000 forward))
            (check "route recorded the preimage" (equalp (getf (gethash (u:sha256 preimage) (cr:courier-routes k)) :preimage) preimage))))))))



(with-gate ("lightning pay path and reference-shaped requests")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*)) (mock-ln (ln:make-mock-ln))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf :ln mock-ln))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a4" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d4")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (d1 (nd:wallet-open-deposit w1 id)) (d2 (nd:wallet-open-deposit w2 id)))
      (nd:credit-onchain a la d1 100000 :txid (u:sha256 (hx "05")))
      ;; bolt11 decoding against a real invoice (cl-payments minted, from the devnet)
      (check-bytes "payment hash read from a real BOLT11"
                   (cl-deposits.lightning.decode:payment-hash "lntbs1230n1p4fe4mnpp5xsy0ed6dr4tum0066kf468m57d8nzdwfym2ct9mm0ghmkxaeq6xqsp5mrgjknqahtx4lj3mphpjf7el9vdatm4p4sm50uuld3ny3zzlj73qdq2wejkxar0wgxqrrsscqpj9qrsgqsc30p2g88av7u6gg040kvdps454u54xgemdqls346l7dhe8x4krs9jz0je67a3n2a3yak3ty5ztgpr47qsfgj5wwevk2yr9sw5hpg6qpj77x6e")
                   (hx "3408fcb74d1d57cdbdfad5935d1f74f34f3135c926d585977b7a2fbb1bb9068c"))
      (check-equal "amount read from the hrp (1230n = 123000 msat)" (cl-deposits.lightning.decode:invoice-amount-msat "lntbs1230n1p4fe4mnpp5xsy0ed6dr4tum0066kf468m57d8nzdwfym2ct9mm0ghmkxaeq6xqsp5mrgjknqahtx4lj3mphpjf7el9vdatm4p4sm50uuld3ny3zzlj73qdq2wejkxar0wgxqrrsscqpj9qrsgqsc30p2g88av7u6gg040kvdps454u54xgemdqls346l7dhe8x4krs9jz0je67a3n2a3yak3ty5ztgpr47qsfgj5wwevk2yr9sw5hpg6qpj77x6e") 123000)
      ;; Pay an external invoice the mock can settle.
      (multiple-value-bind (bolt11 hash preimage) (ln:mock-ln-external-invoice mock-ln 30000)
        (multiple-value-bind (ok pre err) (nd:wallet-pay-invoice w1 id d1 bolt11 30000 :fee 100 :height *height*)
          (check "pay_invoice succeeded" ok err)
          (check-bytes "wallet learns the preimage" pre preimage)
          (check-equal "deposit debited amount + fee, nothing locked" (multiple-value-list (nd:wallet-balance w1 id d1)) '(69900 0))
          (check-equal "fee accumulated" (lg:ledger-fees-accumulated (nd:record-ledger la)) 100)
          (check "InvoiceFulfill carries the preimage"
                 (let ((o (op:decode-operation (up:update-message (first (nd:record-history la))))))
                   (and (eq (op:operation-type o) :invoice-fulfill) (equalp (op:field o :preimage) preimage) (equalp (op:field o :payment-id) hash))))))
      ;; A payment that fails: lock released, InvoiceFail on the chain.
      (multiple-value-bind (ok pre err) (nd:wallet-pay-invoice w1 id d1 (format nil "lnmock19~a" (u:bytes->hex (u:sha256 (hx "dead")))) 5000 :height *height*)
        (declare (ignore pre))
        (check "failed payment reported" (and (not ok) (search "failed" err)))
        (check-equal "funds released after InvoiceFail" (multiple-value-list (nd:wallet-balance w1 id d1)) '(69900 0))
        (check-equal "InvoiceFail recorded" (op:operation-type (op:decode-operation (up:update-message (first (nd:record-history la))))) :invoice-fail))
      ;; Reference-shaped transfer_lock / transfer_complete (field by field, signature).
      (let* ((preimage (u:sha256 (hx "77"))) (hash (u:sha256 preimage)) (nonce (u:sha256 (hx "88")))
             (tid (u:sha256 (u:cat nonce d1 d2)))
             (o (list :type :transfer-lock :transfer-nonce nonce :source-deposit-id d1 :destination-deposit-id d2 :amount 10000 :fee 0
                      :completion-script (format nil "sha256(~a)" (u:bytes->hex hash)) :timeout-height (+ *height* 144) :transfer-id tid
                      :nonce 424242 :expiry (+ *height* 144) :witness '()))
             (sig (first (d17:sign-operation o (nd::wallet-priv w1)))))
        (multiple-value-bind (ok res err)
            (nd:wallet-request w1 id "transfer_lock"
                               (w:json-object "transfer_nonce" (u:bytes->hex nonce) "source_deposit_id" (u:bytes->hex d1) "destination_deposit_id" (u:bytes->hex d2)
                                              "amount" 10000 "fee" 0 "completion_script" (op:field o :completion-script) "timeout_height" (+ *height* 144)
                                              "transfer_id" (u:bytes->hex tid) "op_nonce" 424242 "op_expiry" (+ *height* 144) "signature" (u:bytes->hex sig)))
          (declare (ignore res))
          (check "reference-shaped transfer_lock accepted" ok err))
        (multiple-value-bind (ok res err)
            (nd:wallet-request w2 id "transfer_complete" (w:json-object "transfer_id" (u:bytes->hex tid) "preimage" (u:bytes->hex preimage)))
          (declare (ignore res))
          (check "reference-shaped transfer_complete accepted" ok err))
        (check-equal "balances after the field-by-field transfer" (list (nd:wallet-balance w1 id d1) (nd:wallet-balance w2 id d2)) '(59900 10000))))))



(with-gate ("descriptor deposits: a spending cap enforced by the calculus")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a5" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d5")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (desc (format nil "wsh(and(pk(~a), amount_at_most(60000), blocks_since_open_at_least(5)))" (u:bytes->hex (nd:wallet-pubkey w1))))
           (d1 (nd:wallet-open-deposit w1 id :descriptor desc)) (d2 (nd:wallet-open-deposit w2 id)))
      (check-bytes "deposit id is the descriptor's hash" d1 (op:deposit-id desc))
      (nd:credit-onchain a la d1 200000 :txid (u:sha256 (hx "06")))
      (check-signals "spend too soon after opening is refused" nd:node-error (nd:wallet-transfer w1 id d1 d2 10000 :height *height*))
      (let ((*height* (+ *height* 10)))
        (check-signals "spend above the cap is refused" nd:node-error (nd:wallet-transfer w1 id d1 d2 70000 :height *height*))
        (multiple-value-bind (tid pre) (nd:wallet-transfer w1 id d1 d2 50000 :height *height*)
          (check "spend within the cap after the wait is authorized" (and tid t))
          (nd:wallet-complete-transfer w1 id tid pre)
          (check-equal "balances" (list (nd:wallet-balance w1 id d1) (nd:wallet-balance w2 id d2)) '(150000 50000))))
      (check-signals "an unparseable descriptor cannot open a deposit" nd:node-error
        (nd:wallet-open-deposit w2 id :descriptor "wsh(frob(1))")))))



(with-gate ("respectful dispute on quorum expiry; the winner re-establishes a quorum on its fork")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a6" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m) :membership-blocks 100))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d6")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000 :expiry-blocks 100)
    (let* ((expiry (lg:ledger-quorum-expiry (nd:record-ledger la)))
           (w (nd:make-wallet :priv 55555555555555555555 :bus bus)) (dw (nd:wallet-open-deposit w id)))
      (check-equal "nothing to dispute before expiry" (nd:check-expired-quorums b) '())
      (let ((*height* (+ expiry 1)))
        (check-signals "past expiry, value-moving operations are uncosignable" nd:node-error
          (nd:credit-onchain a la dw 1 :txid (u:sha256 (hx "78"))))
        (check-equal "member b disputes the expired quorum" (nd:check-expired-quorums b) (list id))
        (check "the QuorumExpired proof made c and d fork too"
               (every (lambda (m) (nd:find-fork m id (nd:node-pubkey m))) (list c d)))
        (check "respectful proof type" (fr:respectful-p (fr:make-quorum-expired-proof (nd:node-pubkey a) (u:hex->bytes id) (make-array 32) expiry)))
        ;; Run the lottery through (respectful: obligations to the lottery, change back to the operator).
        (dolist (m (list b c d)) (nd:arm-dispute m (nd:find-fork m id (nd:node-pubkey m))))
        (multiple-value-bind (ctx lottery) (nd:confiscate b id :respectful t)
          (declare (ignore lottery))
          (check-equal "respectful confiscation: lottery output + operator change" (length (btx:tx-outputs ctx)) 2)
          (dolist (m (list b c d)) (nd:publish-reveal m id))
          (let* ((outcomes (mapcar (lambda (m) (multiple-value-list (nd:claim-or-yield m id))) (list b c d)))
                 (winner (nth (position :won outcomes :key #'first) (list b c d)))
                 (wfork (nd:find-fork winner id (nd:node-pubkey winner))))
            (check "a winner took custody" (and winner t))
            ;; Re-establishment: the new custodian stages the other members and begins a quorum on the fork.
            (let ((e (nd:make-node :priv 99999999999999999999 :bus bus :height-fn hf)))
              (nd:open-ledger e :reserves-id "genesis:e6")
              (dolist (m (cons e (remove winner (list b c d))))
                (nd:add-member winner wfork (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m))))
            ;; The deposed operator cannot join: its own expired ledger takes no QuorumJoin.
            (check-signals "the deposed operator's consent fails on its expired ledger" nd:node-error
              (nd:add-member winner wfork (nd:node-pubkey a) :member-ledger-id (nd:record-id-hex la)))
            (check-equal "three members staged on the fork" (length (lg:ledger-next-quorum-members (nd:record-ledger wfork))) 3)
            (multiple-value-bind (qb reserves) (nd:begin-quorum winner wfork :funding-txid (u:sha256 (hx "f00d7")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
              (check "QuorumBegin on the fork cosigned by the staged majority" (>= (length (up:update-cosignatures qb)) 2))
              (check-equal "fork quorum active under the new custodian"
                           (list (lg:ledger-quorum-state (nd:record-ledger wfork)) (equalp (lg:ledger-operator-key (nd:record-ledger wfork)) (nd:node-pubkey winner)))
                           '(:active t))
              (check "new reserves belong to the winner's voter set" (equalp (rs:reserves-operator reserves) (nd:node-pubkey winner))))
            (check "every node replicates the fork at the winner's tip"
                   (every (lambda (m) (let ((f (nd:find-fork m id (nd:node-pubkey winner))))
                                        (and f (equalp (lg:ledger-chain-tip (nd:record-ledger f)) (lg:ledger-chain-tip (nd:record-ledger wfork))))))
                          (remove winner (list a b c d))))))))))



(with-gate ("replacement collateral: declared, verified, and spent into the new vault by the winner")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (chain (make-hash-table :test #'equalp))      ; "txid:vout" -> sats  (a mock chain view)
         (cf (lambda (txid vout) (let ((v (gethash (cons (coerce txid 'list) vout) chain))) (and v (list :value-sats v :confirmations 3)))))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf :chain-fn cf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf :chain-fn cf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf :chain-fn cf))
         (la (nd:open-ledger a :reserves-id "genesis:a7" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (setf (gethash (cons (coerce (u:sha256 (hx "f00d8")) 'list) 0) chain) (floor (+ 15600000 23400000) 1000))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d8")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w (nd:make-wallet :priv 55555555555555555555 :bus bus)) (dw (nd:wallet-open-deposit w id)))
      (nd:credit-onchain a la dw 4000000 :txid (u:sha256 (hx "09")))
      (let ((floor-sats (nd:collateral-floor-sats la)))
        (check-equal "collateral floor = obligations x ratio + claim fee" floor-sats (+ (ceiling (* 4000 3/2)) 400))
        ;; Members fund their own collateral UTXOs (key-path P2TR) on the mock chain, then dispute.
        (dolist (m (list b c d))
          (setf (gethash (cons (coerce (u:sha256 (nd:node-pubkey m)) 'list) 1) chain) (+ floor-sats 1000)))
        (dolist (m (list b c d)) (nd:enter-dispute m la (lg:ledger-sequence (nd:record-ledger la)) :reason "test"))
        (dolist (m (list b c d))
          (nd:arm-dispute m (nd:find-fork m id (nd:node-pubkey m)) :replacement (list (u:sha256 (nd:node-pubkey m)) 1 (+ floor-sats 1000))))
        (check "every armer's collateral is visible" (every (lambda (x) (fourth x)) (nd:armers-of b id)))
        ;; A too-small declaration is refused by the cosigners' rebuild.
        (let ((short (nd:make-node :priv 88888888888888888888 :bus bus :height-fn hf :chain-fn cf)))
          (declare (ignore short)))
        (multiple-value-bind (ctx lottery) (nd:confiscate b id)
          (declare (ignore lottery))
          (check "confiscation signed with collateral checks passing" (and ctx t))
          (dolist (m (list b c d)) (nd:publish-reveal m id))
          (let* ((outcomes (mapcar (lambda (m) (multiple-value-list (nd:claim-or-yield m id))) (list b c d)))
                 (won (find :won outcomes :key #'first)) (claim (second won)))
            (check-equal "claim has two inputs: lottery output + replacement collateral" (length (btx:tx-inputs claim)) 2)
            (check-equal "claim pays lottery + collateral - fee into the new vault"
                         (btx:txout-value (first (btx:tx-outputs claim)))
                         (- (+ (btx:txout-value (first (btx:tx-outputs ctx))) (+ floor-sats 1000)) 400))
            (check "second input is a key-path spend with a 64-byte signature" (= 64 (length (first (second (btx:tx-witnesses claim))))))))
        ;; Missing collateral on chain: confiscation refused.
        (remhash (cons (coerce (u:sha256 (nd:node-pubkey c)) 'list) 1) chain)
        (check-signals "a vanished collateral outpoint blocks the confiscation" nd:node-error (nd:confiscate b id))))))



(with-gate ("couriers: a PTLC route (point locks, courier blinding)")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (e (nd:make-node :priv 99999999999999999999 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (kn (nd:make-node :priv 77777777777777777777 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a8" :reserves 15600000 :collateral 23400000))
         (le (nd:open-ledger e :reserves-id "genesis:e8" :reserves 15600000 :collateral 23400000))
         (ida (nd:record-id-hex la)) (ide (nd:record-id-hex le)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m))))
    (dolist (opnode (list a e))
      (let ((rec (if (eq opnode a) la le)))
        (dolist (m (list b c d)) (nd:add-member opnode rec (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
        (nd:begin-quorum opnode rec :funding-txid (u:sha256 (u:cat (hx "f00d8") (nd:node-pubkey opnode))) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)))
    (let* ((w1 (nd:make-wallet :priv 55555555555555555555 :bus bus)) (w2 (nd:make-wallet :priv 66666666666666666666 :bus bus))
           (kwa (nd:make-wallet :priv 77777777777777777777 :bus bus)) (kwe (nd:make-wallet :priv 77777777777777777777 :bus bus))
           (d1 (nd:wallet-open-deposit w1 ida)) (d2 (nd:wallet-open-deposit w2 ide))
           (ka (nd:wallet-open-deposit kwa ida)) (ke (nd:wallet-open-deposit kwe ide))
           (k (cr:make-courier kn)))
      (nd:credit-onchain a la d1 500000 :txid (u:sha256 (hx "11")))
      (nd:credit-onchain e le ke 800000 :txid (u:sha256 (hx "12")))
      (cr:courier-serve k ida ka kwa) (cr:courier-serve k ide ke kwe)
      (check "pointlock completion accepts the right scalar"
             (nd:completion-satisfied-p (format nil "pointlock(~a)" (u:bytes->hex (up:compressed-pubkey 4242))) (list (u:int->be 4242 32))))
      (check "pointlock completion rejects a wrong scalar"
             (not (nd:completion-satisfied-p (format nil "pointlock(~a)" (u:bytes->hex (up:compressed-pubkey 4242))) (list (u:int->be 4243 32)))))
      (multiple-value-bind (leg1 s forward point-p) (cr:wallet-route w1 (nd:node-pubkey-hex kn) ida ide d1 d2 100000 :height *height* :ptlc t)
        (declare (ignore leg1))
        (let ((leg2 (nd:wallet-pending-lock kn ide nil d2 :point point-p)))
          (check "leg 2 locked to P itself on the destination ledger" (and leg2 t))
          (check "leg 1 and leg 2 lock to different points (unlinkable on the relay)"
                 (let ((l1 (find-if (lambda (p) (equalp (getf p :destination) ka))
                                    (loop for p being the hash-values of (lg:ledger-pending-transfers (nd:record-ledger la)) collect p))))
                   (and l1 (not (string= (getf l1 :completion-script) (format nil "pointlock(~a)" (u:bytes->hex point-p)))))))
          (check "receiver completes leg 2 with s" (nd:wallet-complete-transfer w2 ide (getf leg2 :transfer-id) (u:int->be (u:be->int s) 32)))
          (check-equal "receiver got the forward amount" (nd:wallet-balance w2 ide d2) forward)
          (check-equal "courier completed leg 1 with s + t" (nd:wallet-balance kwa ida ka) 100000)
          (check-equal "sender paid in full" (multiple-value-list (nd:wallet-balance w1 ida d1)) '(400000 0)))))))

(with-gate ("rotation: a ledger that moves between prepare and begin still rotates")
  ;; The soak's cl ledgers never rotated under traffic: funding the reserves
  ;; takes confirmations, transfers chain meanwhile, and begin-quorum refused
  ;; "ledger moved since the reserves were prepared".  The QuorumBegin anchors
  ;; the hash the reserves commit to, which need not be the tip.
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:a9" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00d9")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w (nd:make-wallet :priv 55555555555555555555 :bus bus)) (dw (nd:wallet-open-deposit w id)))
      (dolist (m (list b c d)) (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
      (let* ((reserves (nd:prepare-quorum a la)) (anchor (rs:reserves-ledger-hash reserves)))
        (nd:credit-onchain a la dw 1000 :txid (u:sha256 (hx "79")))
        (check "the ledger moved after prepare" (not (equalp anchor (up:chain-hash (nd::tip la)))))
        (multiple-value-bind (qb r2) (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00da")) :funding-vout 0
                                                          :amount-msats 15600000 :collateral-msats 23400000)
          (let ((o (op:decode-operation (up:update-message qb))))
            (check "rotation commits" (eq (op:operation-type o) :quorum-begin))
            (check-equal "QuorumBegin anchors the prepared hash" (op:field o :ledger-hash) anchor)
            (check-equal "and the reserves it promotes are the prepared ones" (rs:reserves-address r2) (rs:reserves-address reserves))
            (check-equal "cosigners replicated it" (lg:ledger-sequence (nd:record-ledger (nd:find-record b id)))
                         (up:update-seq qb))))))))

(with-gate ("expiry watch: members dispute a lapsed quorum by themselves, after a grace")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:ab" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m) :membership-blocks 100))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00db")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000 :expiry-blocks 100)
    (let ((expiry (lg:ledger-quorum-expiry (nd:record-ledger la))))
      (let ((*height* (+ expiry 1)))
        (check-equal "inside the grace, nobody disputes" (nd:dispute-expired-quorums b :grace 3) '()))
      (let ((*height* (+ expiry 4)))
        (check-equal "past the grace, member b disputes on its own" (nd:dispute-expired-quorums b :grace 3) (list id))
        (check "b forked" (nd:find-fork b id (nd:node-pubkey b)))
        (check-equal "and does not dispute twice" (nd:dispute-expired-quorums b :grace 3) '())
        (check-equal "the operator never disputes its own ledger" (nd:dispute-expired-quorums a :grace 3) '())
        ;; c's replica is behind the relay (it missed the tail): it must not judge.
        (let* ((rec (nd:find-record c id))
               (stale (nd::make-record :id-hex id :ledger (lg:replay (reverse (rest (nd::record-history rec))))
                                       :history (rest (nd::record-history rec)))))
          (setf (gethash id (nd:node-ledgers c)) stale)
          (check-equal "a replica behind the relay does not judge" (nd:dispute-expired-quorums c :grace 3) '())
          (setf (gethash id (nd:node-ledgers c)) rec))
        ;; The operator re-establishes (establishment ops stay cosignable past expiry):
        ;; b, which disputed, stands down.
        (let ((*height* (+ expiry 5)))
          (dolist (m (list c d)) (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
          (nd:add-member a la (nd:node-pubkey b) :member-ledger-id (nd::node-member-ledger-hex b))
          (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00dbb")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
          (check "the quorum was re-established" (> (lg:ledger-quorum-expiry (nd:record-ledger (nd:find-record b id))) *height*))
          (nd:drive-disputes b)
          (check-equal "the DisputeEnter reason is the reference's" 
                       (op:field (nth-value 1 (nd::fork-op (nd:find-fork b id (nd:node-pubkey b)) :dispute-enter)) :reason) "quorum_expired")
          (check "b yielded its now-baseless dispute" (nd::fork-op (nd:find-fork b id (nd:node-pubkey b)) :dispute-yield)))))))

(with-gate ("confiscation signs the tier open at the height: a minority past expiry + 720")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:ac" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m) :membership-blocks 100))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00dc")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000 :expiry-blocks 100)
    (let* ((expiry (lg:ledger-quorum-expiry (nd:record-ledger la)))
           (reserves (nd::disputed-reserves b (nd:find-record b id))))
      (check-equal "just past expiry: Tier 0 (majority)" (nd::confiscation-tier reserves (+ expiry 1)) 0)
      (check-equal "at expiry + 720: Tier 1 (minority)" (nd::confiscation-tier reserves (+ expiry 720)) 1)
      (check "the operator's tie-breaker tier is never chosen"
             (not (rs:tier-tie-breaker-p (nth (nd::confiscation-tier reserves (+ expiry 9000)) (rs:reserves-tiers reserves)))))
      (let ((*height* (+ expiry 721)))
        ;; Only b and c dispute and arm; d stays out.  A majority of four voters is
        ;; out of reach, the Tier-1 minority (one) is not.
        (dolist (m (list b c)) (nd:dispute-expired-quorums m :grace 3) (nd:arm-dispute m (nd:find-fork m id (nd:node-pubkey m))))
        (multiple-value-bind (ctx lottery) (nd:confiscate b id :respectful t)
          (declare (ignore lottery))
          (check-equal "nLockTime is Tier 1's CLTV" (btx:tx-locktime ctx) (+ expiry 720))
          (check "the one-signature Tier-1 spend verifies"
                 (rot:verify-spend ctx 0 (vector (cons (floor (+ 15600000 23400000) 1000) (rs:reserves-spk reserves))))))))))

(with-gate ("collateral wallet: pledge a whole confirmed UTXO, never twice; consolidate when none fits")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (utxos '())
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (nd:make-node :priv 22222222222222222222 :bus bus :height-fn hf :utxos-fn (lambda (addr) (declare (ignore addr)) utxos)))
         (c (nd:make-node :priv 33333333333333333333 :bus bus :height-fn hf))
         (d (nd:make-node :priv 44444444444444444444 :bus bus :height-fn hf))
         (la (nd:open-ledger a :reserves-id "genesis:ad" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m)))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00dd")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000)
    (let* ((w (nd:make-wallet :priv 55555555555555555555 :bus bus)) (dw (nd:wallet-open-deposit w id)))
      (nd:credit-onchain a la dw 1000000 :txid (u:sha256 (hx "c0ffeed"))))
    (let ((need (nd:required-replacement-sats (nd:find-record b id))))
      (check-equal "the reference's floor binds: 1000 sats x 1.5 + 5000" need 6500)
      (flet ((utxo (tag sats conf) (list :txid (u:sha256 (hx tag)) :vout 0 :sats sats :confirmations conf)))
        (setf utxos (list (utxo "01" 4000 3) (utxo "02" 9000 0) (utxo "03" 20000 2) (utxo "04" 7000 5)))
        (let ((p (nd:pledge-collateral b id)))
          (check-equal "smallest confirmed UTXO that covers it, at its full value" (third p) 7000)
          (check-equal "asked again for the same dispute: the same pledge" (nd:pledge-collateral b id) p)
          (let ((other (nd:pledge-collateral b (nd::node-member-ledger-hex b))))
            (check "another dispute gets a different UTXO" (and other (not (equalp (first other) (first p)))))))
        (nd:release-pledges b (nd::node-member-ledger-hex b))
        ;; Nothing single fits, but together they do: consolidate, pledge nothing yet.
        (setf utxos (list (utxo "05" 4000 3) (utxo "06" 3500 1) (utxo "07" 2000 4)))
        (nd:release-pledges b id)
        (check-equal "no single UTXO fits: nothing pledged yet" (nd:pledge-collateral b id) nil)
        (let ((tx (first (nd::node-broadcasts b))))
          (check-equal "a consolidation of all three was broadcast" (length (btx:tx-inputs tx)) 3)
          (check-equal "back to our own key-path address" (btx:txout-script (first (btx:tx-outputs tx)))
                       (lot:key-path-spk (up:x-only (nd:node-pubkey b)))))
        (setf utxos (list (utxo "08" 1000 3)))
        (check-equal "too little altogether: declined" (nd:pledge-collateral b id) nil)))))

(with-gate ("dispute driver: an expired quorum is armed, confiscated, revealed and claimed without a command")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (chain (make-hash-table :test #'equalp))   ; (txid-list . vout) -> (sats . spk)
         (cf (lambda (txid vout) (let ((v (gethash (cons (coerce txid 'list) vout) chain))) (and v (list :value-sats (car v) :confirmations 3)))))
         (bf (lambda (bytes)   ; the mock mempool confirms at once: spend the inputs, add the outputs
               (let ((tx (btx:parse-tx (cl-consensus.wire:make-reader bytes))))
                 (dolist (in (btx:tx-inputs tx)) (remhash (cons (coerce (btx:txin-prev-hash in) 'list) (btx:txin-prev-index in)) chain))
                 (loop for o in (btx:tx-outputs tx) for i from 0
                       do (setf (gethash (cons (coerce (btx:tx-txid tx) 'list) i) chain) (cons (btx:txout-value o) (btx:txout-script o))))
                 (btx:tx-txid tx))))
         (uf-for (lambda (priv)
                   (let ((spk (lot:key-path-spk (up:x-only (up:compressed-pubkey (w:even-y-privkey priv))))))
                     (lambda (addr) (declare (ignore addr))
                       (loop for k being the hash-keys of chain using (hash-value v)
                             when (equalp (cdr v) spk)
                               collect (list :txid (coerce (car k) '(vector (unsigned-byte 8))) :vout (cdr k) :sats (car v) :confirmations 3))))))
         (mk (lambda (priv) (nd:make-node :priv priv :bus bus :height-fn hf :chain-fn cf :broadcast-fn bf :utxos-fn (funcall uf-for priv))))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (funcall mk 22222222222222222222)) (c (funcall mk 33333333333333333333)) (d (funcall mk 44444444444444444444))
         (la (nd:open-ledger a :reserves-id "genesis:ae" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m) :membership-blocks 100))
    (setf (gethash (cons (coerce (u:sha256 (hx "f00de")) 'list) 0) chain) (cons (floor (+ 15600000 23400000) 1000) nil))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00de")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000 :expiry-blocks 100)
    ;; The reserves spk, now that the vault exists.
    (let ((r (nd::disputed-reserves b (nd:find-record b id))))
      (setf (cdr (gethash (cons (coerce (u:sha256 (hx "f00de")) 'list) 0) chain)) (rs:reserves-spk r)))
    ;; Each member's wallet: one coin at its own key-path address.
    (dolist (m (list b c d))
      (setf (gethash (cons (coerce (u:sha256 (nd:node-pubkey m)) 'list) 0) chain) (cons 50000 (lot:key-path-spk (up:x-only (nd:node-pubkey m))))))
    (let ((expiry (lg:ledger-quorum-expiry (nd:record-ledger la))))
      (let ((*height* (+ expiry 4)))
        (dolist (m (list b c d)) (nd:dispute-expired-quorums m :grace 3))
        (dolist (m (list b c d)) (nd:drive-disputes m))
        (check "every member armed by itself, pledging its coin" (= 3 (count-if #'fourth (nd:armers-of b id))))
        (check "each pledge is recorded" (every (lambda (m) (plusp (hash-table-count (nd:node-pledges m)))) (list b c d)))
        (clrhash (nd:node-pledges b))   ; as after a restart that lost pledges.sexp
        (check-equal "a coin declared in our DisputeArmed is never pledged again" (nd:pledge-collateral b (nd::node-member-ledger-hex b)) nil)
        (dolist (m (list b c d)) (nd:drive-disputes m))
        (check "nobody confiscates inside the arm window" (gethash (cons (coerce (u:sha256 (hx "f00de")) 'list) 0) chain)))
      (let ((*height* (+ (nd:dispute-arm-closes b (nd:find-record b id)) 1)))
        (dolist (m (list b c d)) (nd:drive-disputes m))
        (check "the reserves were confiscated" (null (gethash (cons (coerce (u:sha256 (hx "f00de")) 'list) 0) chain)))
        ;; A restart forgets the confiscation and lottery: each member must rebuild
        ;; the (respectful, tiered) transaction from public state to reveal and claim.
        (dolist (m (list b c d))
          (dolist (f (nd::forks-of m id)) (setf (nd::record-confiscation f) nil (nd::record-lottery f) nil)))
        (check "after a restart the confiscation still rebuilds" (nd::confiscation-on-chain c id))
        (loop repeat 3 do (dolist (m (list b c d)) (nd:drive-disputes m)))
        (check "every member revealed" (= 3 (length (nd:reveals-of b id))))
        (let ((acquired (count-if (lambda (m) (nd::fork-op (nd:find-fork m id (nd:node-pubkey m)) :dispute-acquire)) (list b c d)))
              (yielded (count-if (lambda (m) (nd::fork-op (nd:find-fork m id (nd:node-pubkey m)) :dispute-yield)) (list b c d))))
          (check-equal "one winner claimed, the others yielded" (list acquired yielded) '(1 2)))
        (check "every pledge released" (every (lambda (m) (zerop (hash-table-count (nd:node-pledges m)))) (list b c d)))))))

(with-gate ("unclaimable lottery: wait for full arming, then recover through the CSV-144 leaf")
  (let* ((bus (bus:make-mock-bus)) (hf (lambda () *height*))
         (depth 3)
         (chain (make-hash-table :test #'equalp))   ; (txid-list . vout) -> (sats . spk)
         (cf (lambda (txid vout) (let ((v (gethash (cons (coerce txid 'list) vout) chain))) (and v (list :value-sats (car v) :confirmations depth)))))
         (bf (lambda (bytes)
               (let ((tx (btx:parse-tx (cl-consensus.wire:make-reader bytes))))
                 (dolist (in (btx:tx-inputs tx)) (remhash (cons (coerce (btx:txin-prev-hash in) 'list) (btx:txin-prev-index in)) chain))
                 (loop for o in (btx:tx-outputs tx) for i from 0
                       do (setf (gethash (cons (coerce (btx:tx-txid tx) 'list) i) chain) (cons (btx:txout-value o) (btx:txout-script o))))
                 (btx:tx-txid tx))))
         (uf-for (lambda (priv)
                   (let ((spk (lot:key-path-spk (up:x-only (up:compressed-pubkey (w:even-y-privkey priv))))))
                     (lambda (addr) (declare (ignore addr))
                       (loop for k being the hash-keys of chain using (hash-value v)
                             when (equalp (cdr v) spk)
                               collect (list :txid (coerce (car k) '(vector (unsigned-byte 8))) :vout (cdr k) :sats (car v) :confirmations 3))))))
         (mk (lambda (priv) (nd:make-node :priv priv :bus bus :height-fn hf :chain-fn cf :broadcast-fn bf :utxos-fn (funcall uf-for priv))))
         (a (nd:make-node :priv 11111111111111111111 :bus bus :height-fn hf))
         (b (funcall mk 22222222222222222222)) (c (funcall mk 33333333333333333333)) (d (funcall mk 44444444444444444444))
         (la (nd:open-ledger a :reserves-id "genesis:af" :reserves 15600000 :collateral 23400000)) (id (nd:record-id-hex la))
         (reserves-key (cons (coerce (u:sha256 (hx "f00df")) 'list) 0)))
    (dolist (m (list b c d)) (nd:open-ledger m :reserves-id (format nil "genesis:~a" (nd:node-pubkey-hex m)))
      (nd:add-member a la (nd:node-pubkey m) :member-ledger-id (nd::node-member-ledger-hex m) :membership-blocks 100))
    (setf (gethash reserves-key chain) (cons (floor (+ 15600000 23400000) 1000) nil))
    (nd:begin-quorum a la :funding-txid (u:sha256 (hx "f00df")) :funding-vout 0 :amount-msats 15600000 :collateral-msats 23400000 :expiry-blocks 100)
    (setf (cdr (gethash reserves-key chain)) (rs:reserves-spk (nd::disputed-reserves b (nd:find-record b id))))
    (dolist (m (list b c d))
      (setf (gethash (cons (coerce (u:sha256 (nd:node-pubkey m)) 'list) 0) chain) (cons 50000 (lot:key-path-spk (up:x-only (nd:node-pubkey m))))))
    (flet ((seed-with (residue) (loop for i from 0 for sd = (u:sha256 (u:int->be i 4)) when (= residue (mod (u:be->int sd) 3)) return sd))
           (drive () (dolist (m (list b c)) (nd:drive-disputes m))))
      (let ((expiry (lg:ledger-quorum-expiry (nd:record-ledger la))))
        (let ((*height* (+ expiry 4)))
          (dolist (m (list b c)) (nd:dispute-expired-quorums m :grace 3))
          ;; Q = 3, but only b and c arm: b under a preimage of 19 bytes (fine for
          ;; N = 3, out of bounds for the k = 2 claim leaf), c under 17.
          (nd:arm-dispute b (nd:find-fork b id (nd:node-pubkey b)) :seed (seed-with 2) :replacement (nd:pledge-collateral b id))
          (nd:arm-dispute c (nd:find-fork c id (nd:node-pubkey c)) :seed (seed-with 0) :replacement (nd:pledge-collateral c id)))
        (let* ((closes (nd:dispute-arm-closes b (nd:find-record b id))))
          (let ((*height* (+ closes 1)))
            (drive)
            (check "two of three armed: nobody confiscates before the deadline" (gethash reserves-key chain)))
          (let ((*height* (+ closes nd::*full-arming-wait-blocks*)))
            (drive)
            (check "past the deadline the two confiscate" (null (gethash reserves-key chain)))
            (drive)
            (check "both revealed" (= 2 (length (nd:reveals-of b id))))
            (drive)
            (multiple-value-bind (conf lottery) (nd::fork-lottery b id)
              (check "the lottery is recognised as unclaimable" (null (nd::lottery-claimable b id lottery)))
              (check "and left alone before its CSV" (gethash (cons (coerce (btx:tx-txid conf) 'list) 0) chain))
              (setf depth 150)
              (drive)
              (check "past the CSV it is swept" (null (gethash (cons (coerce (btx:tx-txid conf) 'list) 0) chain)))
              (let* ((operator (nth-value 4 (nd::disputed-reserves b (nd:find-record b id))))
                     (spk (u:cat (u:octets 0 20) (cl-consensus.wire:hash160 operator))))
                (check "to the original operator's P2WPKH"
                       (loop for v being the hash-values of chain thereis (equalp (cdr v) spk)))))
            (drive)
            (check "both members concluded and released their pledges"
                   (every (lambda (m) (and (nd::fork-op (nd:find-fork m id (nd:node-pubkey m)) :dispute-yield)
                                           (zerop (hash-table-count (nd:node-pledges m)))))
                          (list b c)))))))))

(report)
