;;;; inspect/rotation-test.lisp — spend the reserves on every tier, validated by
;;;; cl-consensus's script interpreter (the same code that validates blocks).

(in-package #:cl-deposits.test)

(defun test-keys (n) (loop for i from 1 to n collect (+ 1000000007 (* i 987654321))))

(with-gate ("rotation: reserves spends validated by cl-consensus")
  (let* ((privs (test-keys 4))
         (pubs (mapcar #'up:compressed-pubkey privs))
         (keyring (loop for priv in privs for pub in pubs collect (cons (up:x-only pub) priv)))
         (expiry 5000)
         (r (rs:build-reserves :operator (first pubs) :members (rest pubs) :ledger-hash (u:sha256 (hx "aa"))
                               :quorum-expiry expiry :network :signet))
         (amount 39000000)
         (prev-txid (u:sha256 (hx "f00d")))
         (r2 (rs:build-reserves :operator (first pubs) :members (rest pubs) :ledger-hash (u:sha256 (hx "bb"))
                                :quorum-expiry (+ expiry 4000) :network :signet))
         (prevouts (vector (cons amount (rs:reserves-spk r)))))
    (check "signet address is tb1p..." (string= "tb1p" (subseq (rs:reserves-address r) 0 4)))
    (flet ((spend (tier-index signers &key (locktime 0))
             (multiple-value-bind (tx fee)
                 (rot:build-spend :prev-txid prev-txid :prev-vout 0 :reserves-amount amount
                                  :destination-spk (rs:reserves-spk r2)
                                  :splits (list (cons (rot:op-return-script (u:sha256 (hx "cc"))) 0))
                                  :fee-rate 2 :locktime locktime)
               (let* ((ring (remove-if-not (lambda (kv) (member (cdr kv) signers)) keyring))
                      (sigs (rot:sign-tier tx 0 prevouts r tier-index ring))
                      (signed (rot:attach-tier-witness tx 0 r tier-index sigs)))
                 (values (rot:verify-spend signed 0 prevouts) signed fee)))))
      ;; Tier 0: 3-of-4 anytime.
      (multiple-value-bind (ok tx fee) (spend 0 (list (first privs) (second privs) (third privs)))
        (check "tier 0: operator + 2 members (3-of-4) verifies" ok)
        (check-equal "fee is 135+43*2 vbytes at 2 sat/vB" fee (* 2 (+ 135 86)))
        (check-equal "outputs: OP_RETURN anchor then new reserves"
                     (list (aref (btx:txout-script (first (btx:tx-outputs tx))) 0)
                           (equalp (btx:txout-script (second (btx:tx-outputs tx))) (rs:reserves-spk r2)))
                     (list #x6a t))
        (check "effective feerate >= 1 sat/vB despite the reference's optimistic estimate"
               (>= (/ fee (btx:tx-vsize tx)) 1) (format nil "fee ~a vsize ~a" fee (btx:tx-vsize tx))))
      (check "tier 0: 3 members without operator verifies" (spend 0 (rest privs)))
      (check "tier 0: only 2 signers fails" (not (spend 0 (list (second privs) (third privs)))))
      (check "tier 0: 3 sigs with one under a wrong key fails"
             (not (let* ((tx (rot:build-spend :prev-txid prev-txid :prev-vout 0 :reserves-amount amount
                                              :destination-spk (rs:reserves-spk r2) :fee-rate 2))
                         (sigs (rot:sign-tier tx 0 prevouts r 0 keyring)))
                    ;; swap two signatures so each sits under the other's key
                    (rotatef (first sigs) (second sigs))
                    (rot:verify-spend (rot:attach-tier-witness tx 0 r 0 (list (first sigs) (second sigs) (third sigs) nil)) 0 prevouts))))
      ;; Tier 1: 1-of-4 after expiry+720, needs nLockTime.
      (check "tier 1: single member with locktime >= expiry+720 verifies" (spend 1 (list (fourth privs)) :locktime (+ expiry 720)))
      (check "tier 1: single member WITHOUT locktime fails (CLTV)" (not (spend 1 (list (fourth privs)))))
      (check "tier 1: locktime one short fails" (not (spend 1 (list (fourth privs)) :locktime (+ expiry 719))))
      ;; Tier 2: any single voter after expiry+4032.
      (check "tier 2: single member after expiry+4032 verifies" (spend 2 (list (second privs)) :locktime (+ expiry 4032)))
      ;; Tier 3: operator only after expiry+8064.
      (check "tier 3: operator alone after expiry+8064 verifies" (spend 3 (list (first privs)) :locktime (+ expiry 8064)))
      (check "tier 3: a member cannot use the operator leaf" (not (spend 3 (list (second privs)) :locktime (+ expiry 8064))))
      ;; Commitment leaf is unspendable: it ends in OP_0.
      (check "commitment leaf cannot be spent"
             (not (let ((tx (rot:build-spend :prev-txid prev-txid :prev-vout 0 :reserves-amount amount
                                             :destination-spk (rs:reserves-spk r2) :fee-rate 2)))
                    (rot:verify-spend (rot:attach-tier-witness tx 0 r 4 '()) 0 prevouts)))))))



(with-gate ("rotation: vault-spend signers and the UnauthorizedVaultSpend proof")
  (let* ((privs (test-keys 4))
         (pubs (mapcar #'up:compressed-pubkey privs))
         (keyring (loop for priv in privs for pub in pubs collect (cons (up:x-only pub) priv)))
         (r (rs:build-reserves :operator (first pubs) :members (rest pubs) :ledger-hash (u:sha256 (hx "aa"))
                               :quorum-expiry 5000 :network :signet))
         (amount 39000000) (txid (u:sha256 (hx "f00d")))
         (prevouts (vector (cons amount (rs:reserves-spk r)))))
    (flet ((theft (signers)
             (let* ((tx (rot:build-spend :prev-txid txid :prev-vout 0 :reserves-amount amount
                                         :destination-spk (u:octets 0 20 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20) :fee-rate 1))
                    (ring (remove-if-not (lambda (kv) (member (cdr kv) signers)) keyring)))
               (rot:attach-tier-witness tx 0 r 0 (rot:sign-tier tx 0 prevouts r 0 ring)))))
      (let* ((tx (theft (list (first privs) (second privs) (third privs))))
             (signers (fr:vault-spend-signers tx prevouts r txid 0)))
        (check-equal "3-of-4 theft: three verified signers" (length signers) 3)
        (check "the signers are exactly those who signed"
               (every (lambda (p) (member (up:x-only p) signers :test #'equalp)) (subseq pubs 0 3)))
        (check "an input that does not spend the vault outpoint yields none"
               (null (fr:vault-spend-signers tx prevouts r (u:sha256 (hx "beef")) 0)))
        (let ((proof (fr:make-unauthorized-vault-spend-proof (first pubs) (u:sha256 (hx "01")) (u:sha256 (hx "02")) 7 tx prevouts (u:sha256 (hx "03")))))
          (check-equal "discriminant is 10" (fr:proof-discriminant :unauthorized-vault-spend) 10)
          ;; DEP-06 proof_type_byte table, pinned by the vector shared with deposits-rust.
          (with-open-file (in "inspect/vectors/proof_types.txt")
            (let ((n 0))
              (loop for line = (read-line in nil) while line
                    unless (or (zerop (length line)) (char= (char line 0) #\#))
                      do (let* ((sp (position #\Space line)) (byte (parse-integer line :end sp)) (name (subseq line (1+ sp)))
                                (type (car (rassoc name fr::+type-names+ :test #'string=))))
                           (incf n)
                           (check-equal (format nil "wire discriminant of ~a" name) (and type (fr:proof-discriminant type)) byte)))
              (check-equal "the shared vector names all ten proof types" n 10)))
          (check "no embedding required" (not (fr:requires-embedding-p :unauthorized-vault-spend)))
          (let ((back (fr:json->proof (fr:proof->json proof))))
            (check "JSON round trip keeps the proof hash" (equalp (fr:proof-hash proof) (fr:proof-hash back)))
            (check "prevouts survive the round trip" (equal (getf (getf back :evidence) :prevouts) (getf (getf proof :evidence) :prevouts)))))))))

(with-gate ("DEP-20 exits: the shared vector (cl-generated, deposits-rust reproduces it)")
  (let ((cases '()) (cur nil))
    (with-open-file (in (vector-path "exit_settlement.txt"))
      (loop for line = (read-line in nil) while line
            unless (or (zerop (length line)) (char= (char line 0) #\#))
              do (if (and (> (length line) 5) (string= (subseq line 0 5) "case "))
                     (push (setf cur (list (subseq line 5))) cases)
                     (setf (cdr (last cur)) (list line)))))
    (flet ((field (c key) (let ((l (find-if (lambda (l) (and (> (length l) (length key)) (string= (subseq l 0 (1+ (length key))) (format nil "~a " key)))) (cdr c))))
                            (and l (subseq l (1+ (length key)))))))
      (dolist (c cases)
        (let ((name (car c)))
          (cond ((member name '("exit_request" "exit_request_no_expiry" "exit_cancel") :test #'string=)
                 (let* ((tlv (u:hex->bytes (field c "tlv"))) (o (op:decode-operation tlv)))
                   (check-bytes (format nil "~a re-encodes byte for byte" name) (op:encode-operation o) tlv)
                   (check-equal (format nil "~a request id = SHA256(tlv)" name) (u:bytes->hex (u:sha256 tlv)) (field c "id"))
                   (multiple-value-bind (id type args nonce expiry) (d17:operation->dep16 o)
                     (check-equal (format nil "~a DEP-17 sighash" name)
                                  (u:bytes->hex (d17:operation-sighash (d17:operation-preimage id type args nonce expiry)))
                                  (field c "sighash")))
                   (check (format nil "~a witness authorizes under pk(K)" name)
                          (eq :ok (d17:verify-operation-witness o (format nil "pk(~a)" (field c "pubkey")) (op:field o :witness))))))
                ((string= name "quorum_begin_exits")
                 (let* ((tlv (u:hex->bytes (field c "tlv"))) (o (op:decode-operation tlv)))
                   (check-bytes "a QuorumBegin with exits round-trips" (op:encode-operation o) tlv)
                   (check-equal "its exit outputs" (mapcar #'third (op:field o :exit-outputs)) '(1 2))))
                ((string= name "quorum_begin_splice")
                 (let* ((tlv (u:hex->bytes (field c "tlv"))) (o (op:decode-operation tlv)))
                   (check-bytes "a QuorumBegin with a splice-in round-trips" (op:encode-operation o) tlv)
                   (check-equal "its splice amount" (op:field o :splice-in-amount) 70000000)))
                ((string= name "due_set")
                 (let ((l (lg:make-ledger)))
                   (dolist (line (cdr c))
                     (when (string= (subseq line 0 8) "pending ")
                       (destructuring-bind (id amount bh seq exp) (uiop:split-string (subseq line 8) :separator " ")
                         (setf (gethash (u:hex->bytes id) (lg:ledger-pending-exits l))
                               (list :deposit-id (subseq (u:hex->bytes id) 0 16) :amount (parse-integer amount)
                                     :exit-address (u:hex->bytes "00") :expires-at (if (string= exp "-") nil (parse-integer exp))
                                     :block-height (parse-integer bh) :seq (parse-integer seq))))))
                   (check-equal "the due set, in append order"
                                (mapcar (lambda (d) (u:bytes->hex (car d)))
                                        (lg:due-exits l (parse-integer (field c "height")) (parse-integer (field c "cutoff"))))
                                (loop for line in (cdr c) when (string= (subseq line 0 4) "due ")
                                      collect (first (uiop:split-string (subseq line 4) :separator " "))))))
                ((string= name "collateral")
                 (dolist (line (cdr c))
                   (destructuring-bind (res coll v f new) (loop for (nil x) on (uiop:split-string line :separator " ") by #'cddr collect (parse-integer x))
                     (check-equal (format nil "collateral share ~a" line) (floor (* coll (- v f) 1000) (+ res coll)) new))))))))))
